/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.lonjas.service.base;

import avanis.lonjas.model.Lonja;
import avanis.lonjas.service.LonjaService;
import avanis.lonjas.service.LonjaServiceUtil;
import avanis.lonjas.service.persistence.AreaPersistence;
import avanis.lonjas.service.persistence.FechaLonjaPersistence;
import avanis.lonjas.service.persistence.GrupoPersistence;
import avanis.lonjas.service.persistence.LonjaPersistence;
import avanis.lonjas.service.persistence.PrecioLonjaPersistence;
import avanis.lonjas.service.persistence.ProductoExplotPersistence;
import avanis.lonjas.service.persistence.ProductoUserPersistence;
import avanis.lonjas.service.persistence.SubGrupoPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the lonja remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link avanis.lonjas.service.impl.LonjaServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see avanis.lonjas.service.impl.LonjaServiceImpl
 * @generated
 */
public abstract class LonjaServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, LonjaService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LonjaService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>LonjaServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		LonjaServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			LonjaService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		lonjaService = (LonjaService)aopProxy;

		LonjaServiceUtil.setService(lonjaService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LonjaService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Lonja.class;
	}

	protected String getModelClassName() {
		return Lonja.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = lonjaPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected AreaPersistence areaPersistence;

	@Reference
	protected FechaLonjaPersistence fechaLonjaPersistence;

	@Reference
	protected GrupoPersistence grupoPersistence;

	@Reference
	protected avanis.lonjas.service.LonjaLocalService lonjaLocalService;

	protected LonjaService lonjaService;

	@Reference
	protected LonjaPersistence lonjaPersistence;

	@Reference
	protected PrecioLonjaPersistence precioLonjaPersistence;

	@Reference
	protected ProductoExplotPersistence productoExplotPersistence;

	@Reference
	protected ProductoUserPersistence productoUserPersistence;

	@Reference
	protected SubGrupoPersistence subGrupoPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryService
		assetEntryService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagService assetTagService;

	private static final Log _log = LogFactoryUtil.getLog(
		LonjaServiceBaseImpl.class);

}