/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.comunidad.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AnswersUser service. Represents a row in the &quot;AVANIS_COMUNIDAD_AnswersUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>avanis.comunidad.model.impl.AnswersUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>avanis.comunidad.model.impl.AnswersUserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnswersUser
 * @generated
 */
@ProviderType
public interface AnswersUserModel extends BaseModel<AnswersUser> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a answers user model instance should use the {@link AnswersUser} interface instead.
	 */

	/**
	 * Returns the primary key of this answers user.
	 *
	 * @return the primary key of this answers user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this answers user.
	 *
	 * @param primaryKey the primary key of this answers user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this answers user.
	 *
	 * @return the uuid of this answers user
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this answers user.
	 *
	 * @param uuid the uuid of this answers user
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the answer user ID of this answers user.
	 *
	 * @return the answer user ID of this answers user
	 */
	public long getAnswerUserId();

	/**
	 * Sets the answer user ID of this answers user.
	 *
	 * @param answerUserId the answer user ID of this answers user
	 */
	public void setAnswerUserId(long answerUserId);

	/**
	 * Returns the answer user uuid of this answers user.
	 *
	 * @return the answer user uuid of this answers user
	 */
	public String getAnswerUserUuid();

	/**
	 * Sets the answer user uuid of this answers user.
	 *
	 * @param answerUserUuid the answer user uuid of this answers user
	 */
	public void setAnswerUserUuid(String answerUserUuid);

	/**
	 * Returns the answer ID of this answers user.
	 *
	 * @return the answer ID of this answers user
	 */
	public long getAnswerId();

	/**
	 * Sets the answer ID of this answers user.
	 *
	 * @param answerId the answer ID of this answers user
	 */
	public void setAnswerId(long answerId);

	/**
	 * Returns the user ID of this answers user.
	 *
	 * @return the user ID of this answers user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this answers user.
	 *
	 * @param userId the user ID of this answers user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this answers user.
	 *
	 * @return the user uuid of this answers user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this answers user.
	 *
	 * @param userUuid the user uuid of this answers user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the survey ID of this answers user.
	 *
	 * @return the survey ID of this answers user
	 */
	public long getSurveyId();

	/**
	 * Sets the survey ID of this answers user.
	 *
	 * @param surveyId the survey ID of this answers user
	 */
	public void setSurveyId(long surveyId);

	/**
	 * Returns the create date of this answers user.
	 *
	 * @return the create date of this answers user
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this answers user.
	 *
	 * @param createDate the create date of this answers user
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this answers user.
	 *
	 * @return the modified date of this answers user
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this answers user.
	 *
	 * @param modifiedDate the modified date of this answers user
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public AnswersUser cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}