/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.comunidad.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Answers service. Represents a row in the &quot;AVANIS_COMUNIDAD_Answers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>avanis.comunidad.model.impl.AnswersModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>avanis.comunidad.model.impl.AnswersImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Answers
 * @generated
 */
@ProviderType
public interface AnswersModel extends BaseModel<Answers> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a answers model instance should use the {@link Answers} interface instead.
	 */

	/**
	 * Returns the primary key of this answers.
	 *
	 * @return the primary key of this answers
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this answers.
	 *
	 * @param primaryKey the primary key of this answers
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this answers.
	 *
	 * @return the uuid of this answers
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this answers.
	 *
	 * @param uuid the uuid of this answers
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the answer ID of this answers.
	 *
	 * @return the answer ID of this answers
	 */
	public long getAnswerId();

	/**
	 * Sets the answer ID of this answers.
	 *
	 * @param answerId the answer ID of this answers
	 */
	public void setAnswerId(long answerId);

	/**
	 * Returns the survey ID of this answers.
	 *
	 * @return the survey ID of this answers
	 */
	public long getSurveyId();

	/**
	 * Sets the survey ID of this answers.
	 *
	 * @param surveyId the survey ID of this answers
	 */
	public void setSurveyId(long surveyId);

	/**
	 * Returns the answer of this answers.
	 *
	 * @return the answer of this answers
	 */
	@AutoEscape
	public String getAnswer();

	/**
	 * Sets the answer of this answers.
	 *
	 * @param answer the answer of this answers
	 */
	public void setAnswer(String answer);

	/**
	 * Returns the counter answer of this answers.
	 *
	 * @return the counter answer of this answers
	 */
	public int getCounterAnswer();

	/**
	 * Sets the counter answer of this answers.
	 *
	 * @param counterAnswer the counter answer of this answers
	 */
	public void setCounterAnswer(int counterAnswer);

	/**
	 * Returns the create date of this answers.
	 *
	 * @return the create date of this answers
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this answers.
	 *
	 * @param createDate the create date of this answers
	 */
	public void setCreateDate(Date createDate);

	@Override
	public Answers cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}