/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.tu.explotacion.sb.service.base;

import avanis.tu.explotacion.sb.model.Alertas;
import avanis.tu.explotacion.sb.service.AlertasService;
import avanis.tu.explotacion.sb.service.AlertasServiceUtil;
import avanis.tu.explotacion.sb.service.persistence.AlertasPersistence;
import avanis.tu.explotacion.sb.service.persistence.ExplotacionPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the alertas remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link avanis.tu.explotacion.sb.service.impl.AlertasServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see avanis.tu.explotacion.sb.service.impl.AlertasServiceImpl
 * @generated
 */
public abstract class AlertasServiceBaseImpl
	extends BaseServiceImpl
	implements AlertasService, AopService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AlertasService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AlertasServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		AlertasServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AlertasService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		alertasService = (AlertasService)aopProxy;

		AlertasServiceUtil.setService(alertasService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AlertasService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Alertas.class;
	}

	protected String getModelClassName() {
		return Alertas.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = alertasPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected avanis.tu.explotacion.sb.service.AlertasLocalService
		alertasLocalService;

	protected AlertasService alertasService;

	@Reference
	protected AlertasPersistence alertasPersistence;

	@Reference
	protected ExplotacionPersistence explotacionPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		AlertasServiceBaseImpl.class);

}