/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.tu.explotacion.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Explotacion service. Represents a row in the &quot;AVANIS_EXPLOTACION_Explotacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>avanis.tu.explotacion.sb.model.impl.ExplotacionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>avanis.tu.explotacion.sb.model.impl.ExplotacionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Explotacion
 * @generated
 */
@ProviderType
public interface ExplotacionModel extends BaseModel<Explotacion> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a explotacion model instance should use the {@link Explotacion} interface instead.
	 */

	/**
	 * Returns the primary key of this explotacion.
	 *
	 * @return the primary key of this explotacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this explotacion.
	 *
	 * @param primaryKey the primary key of this explotacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this explotacion.
	 *
	 * @return the uuid of this explotacion
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this explotacion.
	 *
	 * @param uuid the uuid of this explotacion
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the explotacion ID of this explotacion.
	 *
	 * @return the explotacion ID of this explotacion
	 */
	public long getExplotacionId();

	/**
	 * Sets the explotacion ID of this explotacion.
	 *
	 * @param explotacionId the explotacion ID of this explotacion
	 */
	public void setExplotacionId(long explotacionId);

	/**
	 * Returns the provincia of this explotacion.
	 *
	 * @return the provincia of this explotacion
	 */
	@AutoEscape
	public String getProvincia();

	/**
	 * Sets the provincia of this explotacion.
	 *
	 * @param provincia the provincia of this explotacion
	 */
	public void setProvincia(String provincia);

	/**
	 * Returns the longitude of this explotacion.
	 *
	 * @return the longitude of this explotacion
	 */
	public Double getLongitude();

	/**
	 * Sets the longitude of this explotacion.
	 *
	 * @param longitude the longitude of this explotacion
	 */
	public void setLongitude(Double longitude);

	/**
	 * Returns the height of this explotacion.
	 *
	 * @return the height of this explotacion
	 */
	public Integer getHeight();

	/**
	 * Sets the height of this explotacion.
	 *
	 * @param height the height of this explotacion
	 */
	public void setHeight(Integer height);

	/**
	 * Returns the location of this explotacion.
	 *
	 * @return the location of this explotacion
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this explotacion.
	 *
	 * @param location the location of this explotacion
	 */
	public void setLocation(String location);

	/**
	 * Returns the name of this explotacion.
	 *
	 * @return the name of this explotacion
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this explotacion.
	 *
	 * @param name the name of this explotacion
	 */
	public void setName(String name);

	/**
	 * Returns the latitude of this explotacion.
	 *
	 * @return the latitude of this explotacion
	 */
	public Double getLatitude();

	/**
	 * Sets the latitude of this explotacion.
	 *
	 * @param latitude the latitude of this explotacion
	 */
	public void setLatitude(Double latitude);

	/**
	 * Returns the meteoredid of this explotacion.
	 *
	 * @return the meteoredid of this explotacion
	 */
	@AutoEscape
	public String getMeteoredid();

	/**
	 * Sets the meteoredid of this explotacion.
	 *
	 * @param meteoredid the meteoredid of this explotacion
	 */
	public void setMeteoredid(String meteoredid);

	/**
	 * Returns the size of this explotacion.
	 *
	 * @return the size of this explotacion
	 */
	public Integer getSize();

	/**
	 * Sets the size of this explotacion.
	 *
	 * @param size the size of this explotacion
	 */
	public void setSize(Integer size);

	/**
	 * Returns the size unit of this explotacion.
	 *
	 * @return the size unit of this explotacion
	 */
	@AutoEscape
	public String getSizeUnit();

	/**
	 * Sets the size unit of this explotacion.
	 *
	 * @param sizeUnit the size unit of this explotacion
	 */
	public void setSizeUnit(String sizeUnit);

	/**
	 * Returns the is main of this explotacion.
	 *
	 * @return the is main of this explotacion
	 */
	public boolean getIsMain();

	/**
	 * Returns <code>true</code> if this explotacion is is main.
	 *
	 * @return <code>true</code> if this explotacion is is main; <code>false</code> otherwise
	 */
	public boolean isIsMain();

	/**
	 * Sets whether this explotacion is is main.
	 *
	 * @param isMain the is main of this explotacion
	 */
	public void setIsMain(boolean isMain);

	/**
	 * Returns the allow notifications of this explotacion.
	 *
	 * @return the allow notifications of this explotacion
	 */
	public boolean getAllowNotifications();

	/**
	 * Returns <code>true</code> if this explotacion is allow notifications.
	 *
	 * @return <code>true</code> if this explotacion is allow notifications; <code>false</code> otherwise
	 */
	public boolean isAllowNotifications();

	/**
	 * Sets whether this explotacion is allow notifications.
	 *
	 * @param allowNotifications the allow notifications of this explotacion
	 */
	public void setAllowNotifications(boolean allowNotifications);

	/**
	 * Returns the user ID of this explotacion.
	 *
	 * @return the user ID of this explotacion
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this explotacion.
	 *
	 * @param userId the user ID of this explotacion
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this explotacion.
	 *
	 * @return the user uuid of this explotacion
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this explotacion.
	 *
	 * @param userUuid the user uuid of this explotacion
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this explotacion.
	 *
	 * @return the user name of this explotacion
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this explotacion.
	 *
	 * @param userName the user name of this explotacion
	 */
	public void setUserName(String userName);

	/**
	 * Returns the readed of this explotacion.
	 *
	 * @return the readed of this explotacion
	 */
	public boolean getReaded();

	/**
	 * Returns <code>true</code> if this explotacion is readed.
	 *
	 * @return <code>true</code> if this explotacion is readed; <code>false</code> otherwise
	 */
	public boolean isReaded();

	/**
	 * Sets whether this explotacion is readed.
	 *
	 * @param readed the readed of this explotacion
	 */
	public void setReaded(boolean readed);

	/**
	 * Returns the create date of this explotacion.
	 *
	 * @return the create date of this explotacion
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this explotacion.
	 *
	 * @param createDate the create date of this explotacion
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this explotacion.
	 *
	 * @return the modified date of this explotacion
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this explotacion.
	 *
	 * @param modifiedDate the modified date of this explotacion
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the external code reference of this explotacion.
	 *
	 * @return the external code reference of this explotacion
	 */
	@AutoEscape
	public String getExternalCodeReference();

	/**
	 * Sets the external code reference of this explotacion.
	 *
	 * @param externalCodeReference the external code reference of this explotacion
	 */
	public void setExternalCodeReference(String externalCodeReference);

	@Override
	public Explotacion cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}