/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.eventos.follow.sb.service.base;

import avanis.eventos.follow.sb.model.EventFollow;
import avanis.eventos.follow.sb.service.EventFollowLocalService;
import avanis.eventos.follow.sb.service.EventFollowLocalServiceUtil;
import avanis.eventos.follow.sb.service.persistence.EventFollowPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the event follow local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link avanis.eventos.follow.sb.service.impl.EventFollowLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see avanis.eventos.follow.sb.service.impl.EventFollowLocalServiceImpl
 * @generated
 */
public abstract class EventFollowLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, EventFollowLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>EventFollowLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>EventFollowLocalServiceUtil</code>.
	 */

	/**
	 * Adds the event follow to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EventFollowLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param eventFollow the event follow
	 * @return the event follow that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EventFollow addEventFollow(EventFollow eventFollow) {
		eventFollow.setNew(true);

		return eventFollowPersistence.update(eventFollow);
	}

	/**
	 * Creates a new event follow with the primary key. Does not add the event follow to the database.
	 *
	 * @param eventFollowId the primary key for the new event follow
	 * @return the new event follow
	 */
	@Override
	@Transactional(enabled = false)
	public EventFollow createEventFollow(long eventFollowId) {
		return eventFollowPersistence.create(eventFollowId);
	}

	/**
	 * Deletes the event follow with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EventFollowLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param eventFollowId the primary key of the event follow
	 * @return the event follow that was removed
	 * @throws PortalException if a event follow with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EventFollow deleteEventFollow(long eventFollowId)
		throws PortalException {

		return eventFollowPersistence.remove(eventFollowId);
	}

	/**
	 * Deletes the event follow from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EventFollowLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param eventFollow the event follow
	 * @return the event follow that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EventFollow deleteEventFollow(EventFollow eventFollow) {
		return eventFollowPersistence.remove(eventFollow);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return eventFollowPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			EventFollow.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return eventFollowPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>avanis.eventos.follow.sb.model.impl.EventFollowModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return eventFollowPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>avanis.eventos.follow.sb.model.impl.EventFollowModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return eventFollowPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return eventFollowPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return eventFollowPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public EventFollow fetchEventFollow(long eventFollowId) {
		return eventFollowPersistence.fetchByPrimaryKey(eventFollowId);
	}

	/**
	 * Returns the event follow matching the UUID and group.
	 *
	 * @param uuid the event follow's UUID
	 * @param groupId the primary key of the group
	 * @return the matching event follow, or <code>null</code> if a matching event follow could not be found
	 */
	@Override
	public EventFollow fetchEventFollowByUuidAndGroupId(
		String uuid, long groupId) {

		return eventFollowPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the event follow with the primary key.
	 *
	 * @param eventFollowId the primary key of the event follow
	 * @return the event follow
	 * @throws PortalException if a event follow with the primary key could not be found
	 */
	@Override
	public EventFollow getEventFollow(long eventFollowId)
		throws PortalException {

		return eventFollowPersistence.findByPrimaryKey(eventFollowId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(eventFollowLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EventFollow.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("eventFollowId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			eventFollowLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(EventFollow.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"eventFollowId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(eventFollowLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EventFollow.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("eventFollowId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<EventFollow>() {

				@Override
				public void performAction(EventFollow eventFollow)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, eventFollow);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(EventFollow.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return eventFollowPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement EventFollowLocalServiceImpl#deleteEventFollow(EventFollow) to avoid orphaned data");
		}

		return eventFollowLocalService.deleteEventFollow(
			(EventFollow)persistedModel);
	}

	@Override
	public BasePersistence<EventFollow> getBasePersistence() {
		return eventFollowPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return eventFollowPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the event follows matching the UUID and company.
	 *
	 * @param uuid the UUID of the event follows
	 * @param companyId the primary key of the company
	 * @return the matching event follows, or an empty list if no matches were found
	 */
	@Override
	public List<EventFollow> getEventFollowsByUuidAndCompanyId(
		String uuid, long companyId) {

		return eventFollowPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of event follows matching the UUID and company.
	 *
	 * @param uuid the UUID of the event follows
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of event follows
	 * @param end the upper bound of the range of event follows (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching event follows, or an empty list if no matches were found
	 */
	@Override
	public List<EventFollow> getEventFollowsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<EventFollow> orderByComparator) {

		return eventFollowPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the event follow matching the UUID and group.
	 *
	 * @param uuid the event follow's UUID
	 * @param groupId the primary key of the group
	 * @return the matching event follow
	 * @throws PortalException if a matching event follow could not be found
	 */
	@Override
	public EventFollow getEventFollowByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return eventFollowPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the event follows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>avanis.eventos.follow.sb.model.impl.EventFollowModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of event follows
	 * @param end the upper bound of the range of event follows (not inclusive)
	 * @return the range of event follows
	 */
	@Override
	public List<EventFollow> getEventFollows(int start, int end) {
		return eventFollowPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of event follows.
	 *
	 * @return the number of event follows
	 */
	@Override
	public int getEventFollowsCount() {
		return eventFollowPersistence.countAll();
	}

	/**
	 * Updates the event follow in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EventFollowLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param eventFollow the event follow
	 * @return the event follow that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EventFollow updateEventFollow(EventFollow eventFollow) {
		return eventFollowPersistence.update(eventFollow);
	}

	@Deactivate
	protected void deactivate() {
		EventFollowLocalServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			EventFollowLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		eventFollowLocalService = (EventFollowLocalService)aopProxy;

		EventFollowLocalServiceUtil.setService(eventFollowLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EventFollowLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return EventFollow.class;
	}

	protected String getModelClassName() {
		return EventFollow.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = eventFollowPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected EventFollowLocalService eventFollowLocalService;

	@Reference
	protected EventFollowPersistence eventFollowPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		EventFollowLocalServiceBaseImpl.class);

}