/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.eventos.follow.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EventFollow service. Represents a row in the &quot;EVENT_FOLLOW_EventFollow&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>avanis.eventos.follow.sb.model.impl.EventFollowModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>avanis.eventos.follow.sb.model.impl.EventFollowImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EventFollow
 * @generated
 */
@ProviderType
public interface EventFollowModel
	extends BaseModel<EventFollow>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event follow model instance should use the {@link EventFollow} interface instead.
	 */

	/**
	 * Returns the primary key of this event follow.
	 *
	 * @return the primary key of this event follow
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this event follow.
	 *
	 * @param primaryKey the primary key of this event follow
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this event follow.
	 *
	 * @return the uuid of this event follow
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this event follow.
	 *
	 * @param uuid the uuid of this event follow
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the event follow ID of this event follow.
	 *
	 * @return the event follow ID of this event follow
	 */
	public long getEventFollowId();

	/**
	 * Sets the event follow ID of this event follow.
	 *
	 * @param eventFollowId the event follow ID of this event follow
	 */
	public void setEventFollowId(long eventFollowId);

	/**
	 * Returns the group ID of this event follow.
	 *
	 * @return the group ID of this event follow
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this event follow.
	 *
	 * @param groupId the group ID of this event follow
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this event follow.
	 *
	 * @return the company ID of this event follow
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this event follow.
	 *
	 * @param companyId the company ID of this event follow
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this event follow.
	 *
	 * @return the user ID of this event follow
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this event follow.
	 *
	 * @param userId the user ID of this event follow
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this event follow.
	 *
	 * @return the user uuid of this event follow
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this event follow.
	 *
	 * @param userUuid the user uuid of this event follow
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this event follow.
	 *
	 * @return the user name of this event follow
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this event follow.
	 *
	 * @param userName the user name of this event follow
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this event follow.
	 *
	 * @return the create date of this event follow
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this event follow.
	 *
	 * @param createDate the create date of this event follow
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this event follow.
	 *
	 * @return the modified date of this event follow
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this event follow.
	 *
	 * @param modifiedDate the modified date of this event follow
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the event ID of this event follow.
	 *
	 * @return the event ID of this event follow
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this event follow.
	 *
	 * @param eventId the event ID of this event follow
	 */
	public void setEventId(long eventId);

	@Override
	public EventFollow cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}