/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.calendarbooking.sb.service.base;

import avanis.calendarbooking.sb.model.BookingAgenda;
import avanis.calendarbooking.sb.service.BookingAgendaLocalService;
import avanis.calendarbooking.sb.service.BookingAgendaLocalServiceUtil;
import avanis.calendarbooking.sb.service.persistence.BookingAgendaPersistence;
import avanis.calendarbooking.sb.service.persistence.ProtagonistPersistence;
import avanis.calendarbooking.sb.service.persistence.SponsorPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the booking agenda local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link avanis.calendarbooking.sb.service.impl.BookingAgendaLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see avanis.calendarbooking.sb.service.impl.BookingAgendaLocalServiceImpl
 * @generated
 */
public abstract class BookingAgendaLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, BookingAgendaLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>BookingAgendaLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>BookingAgendaLocalServiceUtil</code>.
	 */

	/**
	 * Adds the booking agenda to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BookingAgendaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param bookingAgenda the booking agenda
	 * @return the booking agenda that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BookingAgenda addBookingAgenda(BookingAgenda bookingAgenda) {
		bookingAgenda.setNew(true);

		return bookingAgendaPersistence.update(bookingAgenda);
	}

	/**
	 * Creates a new booking agenda with the primary key. Does not add the booking agenda to the database.
	 *
	 * @param calendarBookingAgendaId the primary key for the new booking agenda
	 * @return the new booking agenda
	 */
	@Override
	@Transactional(enabled = false)
	public BookingAgenda createBookingAgenda(long calendarBookingAgendaId) {
		return bookingAgendaPersistence.create(calendarBookingAgendaId);
	}

	/**
	 * Deletes the booking agenda with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BookingAgendaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param calendarBookingAgendaId the primary key of the booking agenda
	 * @return the booking agenda that was removed
	 * @throws PortalException if a booking agenda with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BookingAgenda deleteBookingAgenda(long calendarBookingAgendaId)
		throws PortalException {

		return bookingAgendaPersistence.remove(calendarBookingAgendaId);
	}

	/**
	 * Deletes the booking agenda from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BookingAgendaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param bookingAgenda the booking agenda
	 * @return the booking agenda that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BookingAgenda deleteBookingAgenda(BookingAgenda bookingAgenda) {
		return bookingAgendaPersistence.remove(bookingAgenda);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return bookingAgendaPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			BookingAgenda.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return bookingAgendaPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>avanis.calendarbooking.sb.model.impl.BookingAgendaModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return bookingAgendaPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>avanis.calendarbooking.sb.model.impl.BookingAgendaModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return bookingAgendaPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return bookingAgendaPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return bookingAgendaPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public BookingAgenda fetchBookingAgenda(long calendarBookingAgendaId) {
		return bookingAgendaPersistence.fetchByPrimaryKey(
			calendarBookingAgendaId);
	}

	/**
	 * Returns the booking agenda matching the UUID and group.
	 *
	 * @param uuid the booking agenda's UUID
	 * @param groupId the primary key of the group
	 * @return the matching booking agenda, or <code>null</code> if a matching booking agenda could not be found
	 */
	@Override
	public BookingAgenda fetchBookingAgendaByUuidAndGroupId(
		String uuid, long groupId) {

		return bookingAgendaPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the booking agenda with the primary key.
	 *
	 * @param calendarBookingAgendaId the primary key of the booking agenda
	 * @return the booking agenda
	 * @throws PortalException if a booking agenda with the primary key could not be found
	 */
	@Override
	public BookingAgenda getBookingAgenda(long calendarBookingAgendaId)
		throws PortalException {

		return bookingAgendaPersistence.findByPrimaryKey(
			calendarBookingAgendaId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(bookingAgendaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BookingAgenda.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"calendarBookingAgendaId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			bookingAgendaLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(BookingAgenda.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"calendarBookingAgendaId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(bookingAgendaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BookingAgenda.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"calendarBookingAgendaId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<BookingAgenda>() {

				@Override
				public void performAction(BookingAgenda bookingAgenda)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, bookingAgenda);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(BookingAgenda.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return bookingAgendaPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement BookingAgendaLocalServiceImpl#deleteBookingAgenda(BookingAgenda) to avoid orphaned data");
		}

		return bookingAgendaLocalService.deleteBookingAgenda(
			(BookingAgenda)persistedModel);
	}

	@Override
	public BasePersistence<BookingAgenda> getBasePersistence() {
		return bookingAgendaPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return bookingAgendaPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the booking agendas matching the UUID and company.
	 *
	 * @param uuid the UUID of the booking agendas
	 * @param companyId the primary key of the company
	 * @return the matching booking agendas, or an empty list if no matches were found
	 */
	@Override
	public List<BookingAgenda> getBookingAgendasByUuidAndCompanyId(
		String uuid, long companyId) {

		return bookingAgendaPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of booking agendas matching the UUID and company.
	 *
	 * @param uuid the UUID of the booking agendas
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of booking agendas
	 * @param end the upper bound of the range of booking agendas (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching booking agendas, or an empty list if no matches were found
	 */
	@Override
	public List<BookingAgenda> getBookingAgendasByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<BookingAgenda> orderByComparator) {

		return bookingAgendaPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the booking agenda matching the UUID and group.
	 *
	 * @param uuid the booking agenda's UUID
	 * @param groupId the primary key of the group
	 * @return the matching booking agenda
	 * @throws PortalException if a matching booking agenda could not be found
	 */
	@Override
	public BookingAgenda getBookingAgendaByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return bookingAgendaPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the booking agendas.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>avanis.calendarbooking.sb.model.impl.BookingAgendaModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of booking agendas
	 * @param end the upper bound of the range of booking agendas (not inclusive)
	 * @return the range of booking agendas
	 */
	@Override
	public List<BookingAgenda> getBookingAgendas(int start, int end) {
		return bookingAgendaPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of booking agendas.
	 *
	 * @return the number of booking agendas
	 */
	@Override
	public int getBookingAgendasCount() {
		return bookingAgendaPersistence.countAll();
	}

	/**
	 * Updates the booking agenda in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect BookingAgendaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param bookingAgenda the booking agenda
	 * @return the booking agenda that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BookingAgenda updateBookingAgenda(BookingAgenda bookingAgenda) {
		return bookingAgendaPersistence.update(bookingAgenda);
	}

	@Deactivate
	protected void deactivate() {
		BookingAgendaLocalServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			BookingAgendaLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		bookingAgendaLocalService = (BookingAgendaLocalService)aopProxy;

		BookingAgendaLocalServiceUtil.setService(bookingAgendaLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return BookingAgendaLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return BookingAgenda.class;
	}

	protected String getModelClassName() {
		return BookingAgenda.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = bookingAgendaPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected BookingAgendaLocalService bookingAgendaLocalService;

	@Reference
	protected BookingAgendaPersistence bookingAgendaPersistence;

	@Reference
	protected ProtagonistPersistence protagonistPersistence;

	@Reference
	protected SponsorPersistence sponsorPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		BookingAgendaLocalServiceBaseImpl.class);

}