/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.calendarbooking.sb.service.base;

import avanis.calendarbooking.sb.model.Protagonist;
import avanis.calendarbooking.sb.service.ProtagonistLocalService;
import avanis.calendarbooking.sb.service.ProtagonistLocalServiceUtil;
import avanis.calendarbooking.sb.service.persistence.BookingAgendaPersistence;
import avanis.calendarbooking.sb.service.persistence.ProtagonistPersistence;
import avanis.calendarbooking.sb.service.persistence.SponsorPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the protagonist local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link avanis.calendarbooking.sb.service.impl.ProtagonistLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see avanis.calendarbooking.sb.service.impl.ProtagonistLocalServiceImpl
 * @generated
 */
public abstract class ProtagonistLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, ProtagonistLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ProtagonistLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ProtagonistLocalServiceUtil</code>.
	 */

	/**
	 * Adds the protagonist to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ProtagonistLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param protagonist the protagonist
	 * @return the protagonist that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Protagonist addProtagonist(Protagonist protagonist) {
		protagonist.setNew(true);

		return protagonistPersistence.update(protagonist);
	}

	/**
	 * Creates a new protagonist with the primary key. Does not add the protagonist to the database.
	 *
	 * @param protagonistId the primary key for the new protagonist
	 * @return the new protagonist
	 */
	@Override
	@Transactional(enabled = false)
	public Protagonist createProtagonist(long protagonistId) {
		return protagonistPersistence.create(protagonistId);
	}

	/**
	 * Deletes the protagonist with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ProtagonistLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param protagonistId the primary key of the protagonist
	 * @return the protagonist that was removed
	 * @throws PortalException if a protagonist with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Protagonist deleteProtagonist(long protagonistId)
		throws PortalException {

		return protagonistPersistence.remove(protagonistId);
	}

	/**
	 * Deletes the protagonist from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ProtagonistLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param protagonist the protagonist
	 * @return the protagonist that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Protagonist deleteProtagonist(Protagonist protagonist) {
		return protagonistPersistence.remove(protagonist);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return protagonistPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Protagonist.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return protagonistPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>avanis.calendarbooking.sb.model.impl.ProtagonistModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return protagonistPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>avanis.calendarbooking.sb.model.impl.ProtagonistModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return protagonistPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return protagonistPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return protagonistPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Protagonist fetchProtagonist(long protagonistId) {
		return protagonistPersistence.fetchByPrimaryKey(protagonistId);
	}

	/**
	 * Returns the protagonist matching the UUID and group.
	 *
	 * @param uuid the protagonist's UUID
	 * @param groupId the primary key of the group
	 * @return the matching protagonist, or <code>null</code> if a matching protagonist could not be found
	 */
	@Override
	public Protagonist fetchProtagonistByUuidAndGroupId(
		String uuid, long groupId) {

		return protagonistPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the protagonist with the primary key.
	 *
	 * @param protagonistId the primary key of the protagonist
	 * @return the protagonist
	 * @throws PortalException if a protagonist with the primary key could not be found
	 */
	@Override
	public Protagonist getProtagonist(long protagonistId)
		throws PortalException {

		return protagonistPersistence.findByPrimaryKey(protagonistId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(protagonistLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Protagonist.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("protagonistId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			protagonistLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Protagonist.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"protagonistId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(protagonistLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Protagonist.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("protagonistId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<Protagonist>() {

				@Override
				public void performAction(Protagonist protagonist)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, protagonist);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(Protagonist.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return protagonistPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement ProtagonistLocalServiceImpl#deleteProtagonist(Protagonist) to avoid orphaned data");
		}

		return protagonistLocalService.deleteProtagonist(
			(Protagonist)persistedModel);
	}

	@Override
	public BasePersistence<Protagonist> getBasePersistence() {
		return protagonistPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return protagonistPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the protagonists matching the UUID and company.
	 *
	 * @param uuid the UUID of the protagonists
	 * @param companyId the primary key of the company
	 * @return the matching protagonists, or an empty list if no matches were found
	 */
	@Override
	public List<Protagonist> getProtagonistsByUuidAndCompanyId(
		String uuid, long companyId) {

		return protagonistPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of protagonists matching the UUID and company.
	 *
	 * @param uuid the UUID of the protagonists
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of protagonists
	 * @param end the upper bound of the range of protagonists (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching protagonists, or an empty list if no matches were found
	 */
	@Override
	public List<Protagonist> getProtagonistsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<Protagonist> orderByComparator) {

		return protagonistPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the protagonist matching the UUID and group.
	 *
	 * @param uuid the protagonist's UUID
	 * @param groupId the primary key of the group
	 * @return the matching protagonist
	 * @throws PortalException if a matching protagonist could not be found
	 */
	@Override
	public Protagonist getProtagonistByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return protagonistPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the protagonists.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>avanis.calendarbooking.sb.model.impl.ProtagonistModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of protagonists
	 * @param end the upper bound of the range of protagonists (not inclusive)
	 * @return the range of protagonists
	 */
	@Override
	public List<Protagonist> getProtagonists(int start, int end) {
		return protagonistPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of protagonists.
	 *
	 * @return the number of protagonists
	 */
	@Override
	public int getProtagonistsCount() {
		return protagonistPersistence.countAll();
	}

	/**
	 * Updates the protagonist in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ProtagonistLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param protagonist the protagonist
	 * @return the protagonist that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Protagonist updateProtagonist(Protagonist protagonist) {
		return protagonistPersistence.update(protagonist);
	}

	@Deactivate
	protected void deactivate() {
		ProtagonistLocalServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ProtagonistLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		protagonistLocalService = (ProtagonistLocalService)aopProxy;

		ProtagonistLocalServiceUtil.setService(protagonistLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ProtagonistLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Protagonist.class;
	}

	protected String getModelClassName() {
		return Protagonist.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = protagonistPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected BookingAgendaPersistence bookingAgendaPersistence;

	protected ProtagonistLocalService protagonistLocalService;

	@Reference
	protected ProtagonistPersistence protagonistPersistence;

	@Reference
	protected SponsorPersistence sponsorPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		ProtagonistLocalServiceBaseImpl.class);

}