/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.calendarbooking.sb.service.base;

import avanis.calendarbooking.sb.model.Sponsor;
import avanis.calendarbooking.sb.service.SponsorService;
import avanis.calendarbooking.sb.service.SponsorServiceUtil;
import avanis.calendarbooking.sb.service.persistence.BookingAgendaPersistence;
import avanis.calendarbooking.sb.service.persistence.ProtagonistPersistence;
import avanis.calendarbooking.sb.service.persistence.SponsorPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the sponsor remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link avanis.calendarbooking.sb.service.impl.SponsorServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see avanis.calendarbooking.sb.service.impl.SponsorServiceImpl
 * @generated
 */
public abstract class SponsorServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, SponsorService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SponsorService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>SponsorServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		SponsorServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SponsorService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		sponsorService = (SponsorService)aopProxy;

		SponsorServiceUtil.setService(sponsorService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SponsorService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Sponsor.class;
	}

	protected String getModelClassName() {
		return Sponsor.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = sponsorPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected BookingAgendaPersistence bookingAgendaPersistence;

	@Reference
	protected ProtagonistPersistence protagonistPersistence;

	@Reference
	protected avanis.calendarbooking.sb.service.SponsorLocalService
		sponsorLocalService;

	protected SponsorService sponsorService;

	@Reference
	protected SponsorPersistence sponsorPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		SponsorServiceBaseImpl.class);

}