/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.eventos.follow.sb.model.impl;

import avanis.eventos.follow.sb.model.EventFollow;
import avanis.eventos.follow.sb.service.EventFollowLocalServiceUtil;

/**
 * The extended model base implementation for the EventFollow service. Represents a row in the &quot;EVENT_FOLLOW_EventFollow&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventFollowImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EventFollowImpl
 * @see EventFollow
 * @generated
 */
public abstract class EventFollowBaseImpl
	extends EventFollowModelImpl implements EventFollow {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a event follow model instance should use the <code>EventFollow</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EventFollowLocalServiceUtil.addEventFollow(this);
		}
		else {
			EventFollowLocalServiceUtil.updateEventFollow(this);
		}
	}

}