/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.lonjas.model.impl;

import avanis.lonjas.model.Area;
import avanis.lonjas.model.AreaModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Area service. Represents a row in the &quot;AVANIS_LONJAS_Area&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AreaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AreaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AreaImpl
 * @generated
 */
@JSON(strict = true)
public class AreaModelImpl extends BaseModelImpl<Area> implements AreaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a area model instance should use the <code>Area</code> interface instead.
	 */
	public static final String TABLE_NAME = "AVANIS_LONJAS_Area";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"entityId", Types.BIGINT},
		{"areaId", Types.BIGINT}, {"subGrupoId", Types.BIGINT},
		{"grupoId", Types.BIGINT}, {"nombre", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("areaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subGrupoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("grupoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nombre", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AVANIS_LONJAS_Area (uuid_ VARCHAR(75) null,entityId LONG not null primary key,areaId LONG,subGrupoId LONG,grupoId LONG,nombre VARCHAR(255) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table AVANIS_LONJAS_Area";

	public static final String ORDER_BY_JPQL =
		" ORDER BY area.grupoId ASC, area.subGrupoId ASC, area.areaId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AVANIS_LONJAS_Area.grupoId ASC, AVANIS_LONJAS_Area.subGrupoId ASC, AVANIS_LONJAS_Area.areaId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AREAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOMBRE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GRUPOID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBGRUPOID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AreaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _entityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEntityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _entityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Area.class;
	}

	@Override
	public String getModelClassName() {
		return Area.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Area, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Area, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Area, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Area)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Area, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Area, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Area)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Area, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Area, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Area, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Area, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Area, Object>>();

			attributeGetterFunctions.put("uuid", Area::getUuid);
			attributeGetterFunctions.put("entityId", Area::getEntityId);
			attributeGetterFunctions.put("areaId", Area::getAreaId);
			attributeGetterFunctions.put("subGrupoId", Area::getSubGrupoId);
			attributeGetterFunctions.put("grupoId", Area::getGrupoId);
			attributeGetterFunctions.put("nombre", Area::getNombre);
			attributeGetterFunctions.put("createDate", Area::getCreateDate);
			attributeGetterFunctions.put("modifiedDate", Area::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Area, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Area, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Area, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Area, String>)Area::setUuid);
			attributeSetterBiConsumers.put(
				"entityId", (BiConsumer<Area, Long>)Area::setEntityId);
			attributeSetterBiConsumers.put(
				"areaId", (BiConsumer<Area, Long>)Area::setAreaId);
			attributeSetterBiConsumers.put(
				"subGrupoId", (BiConsumer<Area, Long>)Area::setSubGrupoId);
			attributeSetterBiConsumers.put(
				"grupoId", (BiConsumer<Area, Long>)Area::setGrupoId);
			attributeSetterBiConsumers.put(
				"nombre", (BiConsumer<Area, String>)Area::setNombre);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Area, Date>)Area::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate", (BiConsumer<Area, Date>)Area::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEntityId() {
		return _entityId;
	}

	@Override
	public void setEntityId(long entityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityId = entityId;
	}

	@JSON
	@Override
	public long getAreaId() {
		return _areaId;
	}

	@Override
	public void setAreaId(long areaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_areaId = areaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAreaId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("areaId"));
	}

	@JSON
	@Override
	public long getSubGrupoId() {
		return _subGrupoId;
	}

	@Override
	public void setSubGrupoId(long subGrupoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subGrupoId = subGrupoId;
	}

	@JSON
	@Override
	public long getGrupoId() {
		return _grupoId;
	}

	@Override
	public void setGrupoId(long grupoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_grupoId = grupoId;
	}

	@JSON
	@Override
	public String getNombre() {
		if (_nombre == null) {
			return "";
		}
		else {
			return _nombre;
		}
	}

	@Override
	public void setNombre(String nombre) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nombre = nombre;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNombre() {
		return getColumnOriginalValue("nombre");
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Area.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Area toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Area>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AreaImpl areaImpl = new AreaImpl();

		areaImpl.setUuid(getUuid());
		areaImpl.setEntityId(getEntityId());
		areaImpl.setAreaId(getAreaId());
		areaImpl.setSubGrupoId(getSubGrupoId());
		areaImpl.setGrupoId(getGrupoId());
		areaImpl.setNombre(getNombre());
		areaImpl.setCreateDate(getCreateDate());
		areaImpl.setModifiedDate(getModifiedDate());

		areaImpl.resetOriginalValues();

		return areaImpl;
	}

	@Override
	public Area cloneWithOriginalValues() {
		AreaImpl areaImpl = new AreaImpl();

		areaImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		areaImpl.setEntityId(this.<Long>getColumnOriginalValue("entityId"));
		areaImpl.setAreaId(this.<Long>getColumnOriginalValue("areaId"));
		areaImpl.setSubGrupoId(this.<Long>getColumnOriginalValue("subGrupoId"));
		areaImpl.setGrupoId(this.<Long>getColumnOriginalValue("grupoId"));
		areaImpl.setNombre(this.<String>getColumnOriginalValue("nombre"));
		areaImpl.setCreateDate(this.<Date>getColumnOriginalValue("createDate"));
		areaImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return areaImpl;
	}

	@Override
	public int compareTo(Area area) {
		int value = 0;

		if (getGrupoId() < area.getGrupoId()) {
			value = -1;
		}
		else if (getGrupoId() > area.getGrupoId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getSubGrupoId() < area.getSubGrupoId()) {
			value = -1;
		}
		else if (getSubGrupoId() > area.getSubGrupoId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getAreaId() < area.getAreaId()) {
			value = -1;
		}
		else if (getAreaId() > area.getAreaId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Area)) {
			return false;
		}

		Area area = (Area)object;

		long primaryKey = area.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Area> toCacheModel() {
		AreaCacheModel areaCacheModel = new AreaCacheModel();

		areaCacheModel.uuid = getUuid();

		String uuid = areaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			areaCacheModel.uuid = null;
		}

		areaCacheModel.entityId = getEntityId();

		areaCacheModel.areaId = getAreaId();

		areaCacheModel.subGrupoId = getSubGrupoId();

		areaCacheModel.grupoId = getGrupoId();

		areaCacheModel.nombre = getNombre();

		String nombre = areaCacheModel.nombre;

		if ((nombre != null) && (nombre.length() == 0)) {
			areaCacheModel.nombre = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			areaCacheModel.createDate = createDate.getTime();
		}
		else {
			areaCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			areaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			areaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return areaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Area, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Area, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Area, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Area)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Area>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Area.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _entityId;
	private long _areaId;
	private long _subGrupoId;
	private long _grupoId;
	private String _nombre;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Area, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Area)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("entityId", _entityId);
		_columnOriginalValues.put("areaId", _areaId);
		_columnOriginalValues.put("subGrupoId", _subGrupoId);
		_columnOriginalValues.put("grupoId", _grupoId);
		_columnOriginalValues.put("nombre", _nombre);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("entityId", 2L);

		columnBitmasks.put("areaId", 4L);

		columnBitmasks.put("subGrupoId", 8L);

		columnBitmasks.put("grupoId", 16L);

		columnBitmasks.put("nombre", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Area _escapedModel;

}