/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.lonjas.model.impl;

import avanis.lonjas.model.ProductoUser;
import avanis.lonjas.model.ProductoUserModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProductoUser service. Represents a row in the &quot;AVANIS_LONJAS_ProductoUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProductoUserModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductoUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductoUserImpl
 * @generated
 */
@JSON(strict = true)
public class ProductoUserModelImpl
	extends BaseModelImpl<ProductoUser> implements ProductoUserModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a producto user model instance should use the <code>ProductoUser</code> interface instead.
	 */
	public static final String TABLE_NAME = "AVANIS_LONJAS_ProductoUser";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"entityId", Types.BIGINT},
		{"lonjaId", Types.BIGINT}, {"productoId", Types.BIGINT},
		{"precioLonjaId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"orden", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lonjaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("precioLonjaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("orden", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AVANIS_LONJAS_ProductoUser (uuid_ VARCHAR(75) null,entityId LONG not null primary key,lonjaId LONG,productoId LONG,precioLonjaId LONG,userId LONG,orden LONG,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table AVANIS_LONJAS_ProductoUser";

	public static final String ORDER_BY_JPQL =
		" ORDER BY productoUser.userId ASC, productoUser.orden ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AVANIS_LONJAS_ProductoUser.userId ASC, AVANIS_LONJAS_ProductoUser.orden ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LONJAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRODUCTOID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ORDEN_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProductoUserModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _entityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEntityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _entityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProductoUser.class;
	}

	@Override
	public String getModelClassName() {
		return ProductoUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProductoUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProductoUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductoUser, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProductoUser)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProductoUser, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProductoUser, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProductoUser)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProductoUser, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProductoUser, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ProductoUser, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ProductoUser, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<ProductoUser, Object>>();

			attributeGetterFunctions.put("uuid", ProductoUser::getUuid);
			attributeGetterFunctions.put("entityId", ProductoUser::getEntityId);
			attributeGetterFunctions.put("lonjaId", ProductoUser::getLonjaId);
			attributeGetterFunctions.put(
				"productoId", ProductoUser::getProductoId);
			attributeGetterFunctions.put(
				"precioLonjaId", ProductoUser::getPrecioLonjaId);
			attributeGetterFunctions.put("userId", ProductoUser::getUserId);
			attributeGetterFunctions.put("orden", ProductoUser::getOrden);
			attributeGetterFunctions.put(
				"createDate", ProductoUser::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ProductoUser::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ProductoUser, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ProductoUser, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<ProductoUser, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<ProductoUser, String>)ProductoUser::setUuid);
			attributeSetterBiConsumers.put(
				"entityId",
				(BiConsumer<ProductoUser, Long>)ProductoUser::setEntityId);
			attributeSetterBiConsumers.put(
				"lonjaId",
				(BiConsumer<ProductoUser, Long>)ProductoUser::setLonjaId);
			attributeSetterBiConsumers.put(
				"productoId",
				(BiConsumer<ProductoUser, Long>)ProductoUser::setProductoId);
			attributeSetterBiConsumers.put(
				"precioLonjaId",
				(BiConsumer<ProductoUser, Long>)ProductoUser::setPrecioLonjaId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<ProductoUser, Long>)ProductoUser::setUserId);
			attributeSetterBiConsumers.put(
				"orden",
				(BiConsumer<ProductoUser, Long>)ProductoUser::setOrden);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ProductoUser, Date>)ProductoUser::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ProductoUser, Date>)ProductoUser::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEntityId() {
		return _entityId;
	}

	@Override
	public void setEntityId(long entityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityId = entityId;
	}

	@JSON
	@Override
	public long getLonjaId() {
		return _lonjaId;
	}

	@Override
	public void setLonjaId(long lonjaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lonjaId = lonjaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLonjaId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("lonjaId"));
	}

	@JSON
	@Override
	public long getProductoId() {
		return _productoId;
	}

	@Override
	public void setProductoId(long productoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_productoId = productoId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProductoId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("productoId"));
	}

	@JSON
	@Override
	public long getPrecioLonjaId() {
		return _precioLonjaId;
	}

	@Override
	public void setPrecioLonjaId(long precioLonjaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_precioLonjaId = precioLonjaId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public long getOrden() {
		return _orden;
	}

	@Override
	public void setOrden(long orden) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_orden = orden;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ProductoUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProductoUser toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProductoUser>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProductoUserImpl productoUserImpl = new ProductoUserImpl();

		productoUserImpl.setUuid(getUuid());
		productoUserImpl.setEntityId(getEntityId());
		productoUserImpl.setLonjaId(getLonjaId());
		productoUserImpl.setProductoId(getProductoId());
		productoUserImpl.setPrecioLonjaId(getPrecioLonjaId());
		productoUserImpl.setUserId(getUserId());
		productoUserImpl.setOrden(getOrden());
		productoUserImpl.setCreateDate(getCreateDate());
		productoUserImpl.setModifiedDate(getModifiedDate());

		productoUserImpl.resetOriginalValues();

		return productoUserImpl;
	}

	@Override
	public ProductoUser cloneWithOriginalValues() {
		ProductoUserImpl productoUserImpl = new ProductoUserImpl();

		productoUserImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		productoUserImpl.setEntityId(
			this.<Long>getColumnOriginalValue("entityId"));
		productoUserImpl.setLonjaId(
			this.<Long>getColumnOriginalValue("lonjaId"));
		productoUserImpl.setProductoId(
			this.<Long>getColumnOriginalValue("productoId"));
		productoUserImpl.setPrecioLonjaId(
			this.<Long>getColumnOriginalValue("precioLonjaId"));
		productoUserImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		productoUserImpl.setOrden(this.<Long>getColumnOriginalValue("orden"));
		productoUserImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		productoUserImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return productoUserImpl;
	}

	@Override
	public int compareTo(ProductoUser productoUser) {
		int value = 0;

		if (getUserId() < productoUser.getUserId()) {
			value = -1;
		}
		else if (getUserId() > productoUser.getUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getOrden() < productoUser.getOrden()) {
			value = -1;
		}
		else if (getOrden() > productoUser.getOrden()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProductoUser)) {
			return false;
		}

		ProductoUser productoUser = (ProductoUser)object;

		long primaryKey = productoUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProductoUser> toCacheModel() {
		ProductoUserCacheModel productoUserCacheModel =
			new ProductoUserCacheModel();

		productoUserCacheModel.uuid = getUuid();

		String uuid = productoUserCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			productoUserCacheModel.uuid = null;
		}

		productoUserCacheModel.entityId = getEntityId();

		productoUserCacheModel.lonjaId = getLonjaId();

		productoUserCacheModel.productoId = getProductoId();

		productoUserCacheModel.precioLonjaId = getPrecioLonjaId();

		productoUserCacheModel.userId = getUserId();

		productoUserCacheModel.orden = getOrden();

		Date createDate = getCreateDate();

		if (createDate != null) {
			productoUserCacheModel.createDate = createDate.getTime();
		}
		else {
			productoUserCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			productoUserCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			productoUserCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return productoUserCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProductoUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProductoUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductoUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ProductoUser)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProductoUser>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProductoUser.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _entityId;
	private long _lonjaId;
	private long _productoId;
	private long _precioLonjaId;
	private long _userId;
	private long _orden;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProductoUser, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProductoUser)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("entityId", _entityId);
		_columnOriginalValues.put("lonjaId", _lonjaId);
		_columnOriginalValues.put("productoId", _productoId);
		_columnOriginalValues.put("precioLonjaId", _precioLonjaId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("orden", _orden);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("entityId", 2L);

		columnBitmasks.put("lonjaId", 4L);

		columnBitmasks.put("productoId", 8L);

		columnBitmasks.put("precioLonjaId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("orden", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProductoUser _escapedModel;

}