/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.lonjas.model.impl;

import avanis.lonjas.model.ProductoExplot;
import avanis.lonjas.model.ProductoExplotModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProductoExplot service. Represents a row in the &quot;AVANIS_LONJAS_ProductoExplot&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProductoExplotModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductoExplotImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductoExplotImpl
 * @generated
 */
@JSON(strict = true)
public class ProductoExplotModelImpl
	extends BaseModelImpl<ProductoExplot> implements ProductoExplotModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a producto explot model instance should use the <code>ProductoExplot</code> interface instead.
	 */
	public static final String TABLE_NAME = "AVANIS_LONJAS_ProductoExplot";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"entityId", Types.BIGINT},
		{"lonjaId", Types.BIGINT}, {"productoId", Types.BIGINT},
		{"precioLonjaId", Types.BIGINT}, {"explotacionId", Types.BIGINT},
		{"orden", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lonjaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("precioLonjaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("explotacionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("orden", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AVANIS_LONJAS_ProductoExplot (uuid_ VARCHAR(75) null,entityId LONG not null primary key,lonjaId LONG,productoId LONG,precioLonjaId LONG,explotacionId LONG,orden LONG,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table AVANIS_LONJAS_ProductoExplot";

	public static final String ORDER_BY_JPQL =
		" ORDER BY productoExplot.explotacionId ASC, productoExplot.orden ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AVANIS_LONJAS_ProductoExplot.explotacionId ASC, AVANIS_LONJAS_ProductoExplot.orden ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXPLOTACIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ORDEN_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProductoExplotModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _entityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEntityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _entityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProductoExplot.class;
	}

	@Override
	public String getModelClassName() {
		return ProductoExplot.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProductoExplot, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProductoExplot, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductoExplot, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProductoExplot)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProductoExplot, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProductoExplot, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProductoExplot)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProductoExplot, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProductoExplot, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ProductoExplot, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ProductoExplot, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ProductoExplot, Object>>();

			attributeGetterFunctions.put("uuid", ProductoExplot::getUuid);
			attributeGetterFunctions.put(
				"entityId", ProductoExplot::getEntityId);
			attributeGetterFunctions.put("lonjaId", ProductoExplot::getLonjaId);
			attributeGetterFunctions.put(
				"productoId", ProductoExplot::getProductoId);
			attributeGetterFunctions.put(
				"precioLonjaId", ProductoExplot::getPrecioLonjaId);
			attributeGetterFunctions.put(
				"explotacionId", ProductoExplot::getExplotacionId);
			attributeGetterFunctions.put("orden", ProductoExplot::getOrden);
			attributeGetterFunctions.put(
				"createDate", ProductoExplot::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ProductoExplot::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ProductoExplot, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ProductoExplot, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<ProductoExplot, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<ProductoExplot, String>)ProductoExplot::setUuid);
			attributeSetterBiConsumers.put(
				"entityId",
				(BiConsumer<ProductoExplot, Long>)ProductoExplot::setEntityId);
			attributeSetterBiConsumers.put(
				"lonjaId",
				(BiConsumer<ProductoExplot, Long>)ProductoExplot::setLonjaId);
			attributeSetterBiConsumers.put(
				"productoId",
				(BiConsumer<ProductoExplot, Long>)
					ProductoExplot::setProductoId);
			attributeSetterBiConsumers.put(
				"precioLonjaId",
				(BiConsumer<ProductoExplot, Long>)
					ProductoExplot::setPrecioLonjaId);
			attributeSetterBiConsumers.put(
				"explotacionId",
				(BiConsumer<ProductoExplot, Long>)
					ProductoExplot::setExplotacionId);
			attributeSetterBiConsumers.put(
				"orden",
				(BiConsumer<ProductoExplot, Long>)ProductoExplot::setOrden);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ProductoExplot, Date>)
					ProductoExplot::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ProductoExplot, Date>)
					ProductoExplot::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEntityId() {
		return _entityId;
	}

	@Override
	public void setEntityId(long entityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityId = entityId;
	}

	@JSON
	@Override
	public long getLonjaId() {
		return _lonjaId;
	}

	@Override
	public void setLonjaId(long lonjaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lonjaId = lonjaId;
	}

	@JSON
	@Override
	public long getProductoId() {
		return _productoId;
	}

	@Override
	public void setProductoId(long productoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_productoId = productoId;
	}

	@JSON
	@Override
	public long getPrecioLonjaId() {
		return _precioLonjaId;
	}

	@Override
	public void setPrecioLonjaId(long precioLonjaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_precioLonjaId = precioLonjaId;
	}

	@JSON
	@Override
	public long getExplotacionId() {
		return _explotacionId;
	}

	@Override
	public void setExplotacionId(long explotacionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_explotacionId = explotacionId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalExplotacionId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("explotacionId"));
	}

	@JSON
	@Override
	public long getOrden() {
		return _orden;
	}

	@Override
	public void setOrden(long orden) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_orden = orden;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ProductoExplot.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProductoExplot toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProductoExplot>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProductoExplotImpl productoExplotImpl = new ProductoExplotImpl();

		productoExplotImpl.setUuid(getUuid());
		productoExplotImpl.setEntityId(getEntityId());
		productoExplotImpl.setLonjaId(getLonjaId());
		productoExplotImpl.setProductoId(getProductoId());
		productoExplotImpl.setPrecioLonjaId(getPrecioLonjaId());
		productoExplotImpl.setExplotacionId(getExplotacionId());
		productoExplotImpl.setOrden(getOrden());
		productoExplotImpl.setCreateDate(getCreateDate());
		productoExplotImpl.setModifiedDate(getModifiedDate());

		productoExplotImpl.resetOriginalValues();

		return productoExplotImpl;
	}

	@Override
	public ProductoExplot cloneWithOriginalValues() {
		ProductoExplotImpl productoExplotImpl = new ProductoExplotImpl();

		productoExplotImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		productoExplotImpl.setEntityId(
			this.<Long>getColumnOriginalValue("entityId"));
		productoExplotImpl.setLonjaId(
			this.<Long>getColumnOriginalValue("lonjaId"));
		productoExplotImpl.setProductoId(
			this.<Long>getColumnOriginalValue("productoId"));
		productoExplotImpl.setPrecioLonjaId(
			this.<Long>getColumnOriginalValue("precioLonjaId"));
		productoExplotImpl.setExplotacionId(
			this.<Long>getColumnOriginalValue("explotacionId"));
		productoExplotImpl.setOrden(this.<Long>getColumnOriginalValue("orden"));
		productoExplotImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		productoExplotImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return productoExplotImpl;
	}

	@Override
	public int compareTo(ProductoExplot productoExplot) {
		int value = 0;

		if (getExplotacionId() < productoExplot.getExplotacionId()) {
			value = -1;
		}
		else if (getExplotacionId() > productoExplot.getExplotacionId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getOrden() < productoExplot.getOrden()) {
			value = -1;
		}
		else if (getOrden() > productoExplot.getOrden()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProductoExplot)) {
			return false;
		}

		ProductoExplot productoExplot = (ProductoExplot)object;

		long primaryKey = productoExplot.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProductoExplot> toCacheModel() {
		ProductoExplotCacheModel productoExplotCacheModel =
			new ProductoExplotCacheModel();

		productoExplotCacheModel.uuid = getUuid();

		String uuid = productoExplotCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			productoExplotCacheModel.uuid = null;
		}

		productoExplotCacheModel.entityId = getEntityId();

		productoExplotCacheModel.lonjaId = getLonjaId();

		productoExplotCacheModel.productoId = getProductoId();

		productoExplotCacheModel.precioLonjaId = getPrecioLonjaId();

		productoExplotCacheModel.explotacionId = getExplotacionId();

		productoExplotCacheModel.orden = getOrden();

		Date createDate = getCreateDate();

		if (createDate != null) {
			productoExplotCacheModel.createDate = createDate.getTime();
		}
		else {
			productoExplotCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			productoExplotCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			productoExplotCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return productoExplotCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProductoExplot, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProductoExplot, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductoExplot, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ProductoExplot)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProductoExplot>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProductoExplot.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _entityId;
	private long _lonjaId;
	private long _productoId;
	private long _precioLonjaId;
	private long _explotacionId;
	private long _orden;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProductoExplot, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProductoExplot)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("entityId", _entityId);
		_columnOriginalValues.put("lonjaId", _lonjaId);
		_columnOriginalValues.put("productoId", _productoId);
		_columnOriginalValues.put("precioLonjaId", _precioLonjaId);
		_columnOriginalValues.put("explotacionId", _explotacionId);
		_columnOriginalValues.put("orden", _orden);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("entityId", 2L);

		columnBitmasks.put("lonjaId", 4L);

		columnBitmasks.put("productoId", 8L);

		columnBitmasks.put("precioLonjaId", 16L);

		columnBitmasks.put("explotacionId", 32L);

		columnBitmasks.put("orden", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProductoExplot _escapedModel;

}