/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.lonjas.model.impl;

import avanis.lonjas.model.ProductoUser;
import avanis.lonjas.service.ProductoUserLocalServiceUtil;

/**
 * The extended model base implementation for the ProductoUser service. Represents a row in the &quot;AVANIS_LONJAS_ProductoUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductoUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductoUserImpl
 * @see ProductoUser
 * @generated
 */
public abstract class ProductoUserBaseImpl
	extends ProductoUserModelImpl implements ProductoUser {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a producto user model instance should use the <code>ProductoUser</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ProductoUserLocalServiceUtil.addProductoUser(this);
		}
		else {
			ProductoUserLocalServiceUtil.updateProductoUser(this);
		}
	}

}