/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.lonjas.model.impl;

import avanis.lonjas.model.SubGrupo;
import avanis.lonjas.service.SubGrupoLocalServiceUtil;

/**
 * The extended model base implementation for the SubGrupo service. Represents a row in the &quot;AVANIS_LONJAS_SubGrupo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubGrupoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubGrupoImpl
 * @see SubGrupo
 * @generated
 */
public abstract class SubGrupoBaseImpl
	extends SubGrupoModelImpl implements SubGrupo {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sub grupo model instance should use the <code>SubGrupo</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SubGrupoLocalServiceUtil.addSubGrupo(this);
		}
		else {
			SubGrupoLocalServiceUtil.updateSubGrupo(this);
		}
	}

}