/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.social.follow.sb.model.impl;

import avanis.social.follow.sb.model.SocialFollow;
import avanis.social.follow.sb.model.SocialFollowModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SocialFollow service. Represents a row in the &quot;SOCIAL_FOLLOW_SocialFollow&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SocialFollowModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SocialFollowImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SocialFollowImpl
 * @generated
 */
@JSON(strict = true)
public class SocialFollowModelImpl
	extends BaseModelImpl<SocialFollow> implements SocialFollowModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a social follow model instance should use the <code>SocialFollow</code> interface instead.
	 */
	public static final String TABLE_NAME = "SOCIAL_FOLLOW_SocialFollow";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"socialFollowId", Types.BIGINT},
		{"accepted", Types.BOOLEAN}, {"followsTo", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("socialFollowId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("accepted", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("followsTo", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SOCIAL_FOLLOW_SocialFollow (uuid_ VARCHAR(75) null,socialFollowId LONG not null primary key,accepted BOOLEAN,followsTo LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table SOCIAL_FOLLOW_SocialFollow";

	public static final String ORDER_BY_JPQL =
		" ORDER BY socialFollow.socialFollowId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SOCIAL_FOLLOW_SocialFollow.socialFollowId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACCEPTED_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FOLLOWSTO_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SOCIALFOLLOWID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SocialFollowModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _socialFollowId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSocialFollowId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _socialFollowId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SocialFollow.class;
	}

	@Override
	public String getModelClassName() {
		return SocialFollow.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SocialFollow, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SocialFollow, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SocialFollow, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SocialFollow)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SocialFollow, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SocialFollow, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SocialFollow)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SocialFollow, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SocialFollow, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<SocialFollow, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<SocialFollow, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<SocialFollow, Object>>();

			attributeGetterFunctions.put("uuid", SocialFollow::getUuid);
			attributeGetterFunctions.put(
				"socialFollowId", SocialFollow::getSocialFollowId);
			attributeGetterFunctions.put("accepted", SocialFollow::getAccepted);
			attributeGetterFunctions.put(
				"followsTo", SocialFollow::getFollowsTo);
			attributeGetterFunctions.put("groupId", SocialFollow::getGroupId);
			attributeGetterFunctions.put(
				"companyId", SocialFollow::getCompanyId);
			attributeGetterFunctions.put("userId", SocialFollow::getUserId);
			attributeGetterFunctions.put("userName", SocialFollow::getUserName);
			attributeGetterFunctions.put(
				"createDate", SocialFollow::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", SocialFollow::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<SocialFollow, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<SocialFollow, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<SocialFollow, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<SocialFollow, String>)SocialFollow::setUuid);
			attributeSetterBiConsumers.put(
				"socialFollowId",
				(BiConsumer<SocialFollow, Long>)
					SocialFollow::setSocialFollowId);
			attributeSetterBiConsumers.put(
				"accepted",
				(BiConsumer<SocialFollow, Boolean>)SocialFollow::setAccepted);
			attributeSetterBiConsumers.put(
				"followsTo",
				(BiConsumer<SocialFollow, Long>)SocialFollow::setFollowsTo);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<SocialFollow, Long>)SocialFollow::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<SocialFollow, Long>)SocialFollow::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<SocialFollow, Long>)SocialFollow::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<SocialFollow, String>)SocialFollow::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<SocialFollow, Date>)SocialFollow::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<SocialFollow, Date>)SocialFollow::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getSocialFollowId() {
		return _socialFollowId;
	}

	@Override
	public void setSocialFollowId(long socialFollowId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_socialFollowId = socialFollowId;
	}

	@JSON
	@Override
	public boolean getAccepted() {
		return _accepted;
	}

	@JSON
	@Override
	public boolean isAccepted() {
		return _accepted;
	}

	@Override
	public void setAccepted(boolean accepted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accepted = accepted;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalAccepted() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("accepted"));
	}

	@JSON
	@Override
	public long getFollowsTo() {
		return _followsTo;
	}

	@Override
	public void setFollowsTo(long followsTo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_followsTo = followsTo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFollowsTo() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("followsTo"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(SocialFollow.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SocialFollow.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SocialFollow toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SocialFollow>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SocialFollowImpl socialFollowImpl = new SocialFollowImpl();

		socialFollowImpl.setUuid(getUuid());
		socialFollowImpl.setSocialFollowId(getSocialFollowId());
		socialFollowImpl.setAccepted(isAccepted());
		socialFollowImpl.setFollowsTo(getFollowsTo());
		socialFollowImpl.setGroupId(getGroupId());
		socialFollowImpl.setCompanyId(getCompanyId());
		socialFollowImpl.setUserId(getUserId());
		socialFollowImpl.setUserName(getUserName());
		socialFollowImpl.setCreateDate(getCreateDate());
		socialFollowImpl.setModifiedDate(getModifiedDate());

		socialFollowImpl.resetOriginalValues();

		return socialFollowImpl;
	}

	@Override
	public SocialFollow cloneWithOriginalValues() {
		SocialFollowImpl socialFollowImpl = new SocialFollowImpl();

		socialFollowImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		socialFollowImpl.setSocialFollowId(
			this.<Long>getColumnOriginalValue("socialFollowId"));
		socialFollowImpl.setAccepted(
			this.<Boolean>getColumnOriginalValue("accepted"));
		socialFollowImpl.setFollowsTo(
			this.<Long>getColumnOriginalValue("followsTo"));
		socialFollowImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		socialFollowImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		socialFollowImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		socialFollowImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		socialFollowImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		socialFollowImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return socialFollowImpl;
	}

	@Override
	public int compareTo(SocialFollow socialFollow) {
		long primaryKey = socialFollow.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SocialFollow)) {
			return false;
		}

		SocialFollow socialFollow = (SocialFollow)object;

		long primaryKey = socialFollow.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SocialFollow> toCacheModel() {
		SocialFollowCacheModel socialFollowCacheModel =
			new SocialFollowCacheModel();

		socialFollowCacheModel.uuid = getUuid();

		String uuid = socialFollowCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			socialFollowCacheModel.uuid = null;
		}

		socialFollowCacheModel.socialFollowId = getSocialFollowId();

		socialFollowCacheModel.accepted = isAccepted();

		socialFollowCacheModel.followsTo = getFollowsTo();

		socialFollowCacheModel.groupId = getGroupId();

		socialFollowCacheModel.companyId = getCompanyId();

		socialFollowCacheModel.userId = getUserId();

		socialFollowCacheModel.userName = getUserName();

		String userName = socialFollowCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			socialFollowCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			socialFollowCacheModel.createDate = createDate.getTime();
		}
		else {
			socialFollowCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			socialFollowCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			socialFollowCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return socialFollowCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SocialFollow, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SocialFollow, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SocialFollow, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SocialFollow)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SocialFollow>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SocialFollow.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _socialFollowId;
	private boolean _accepted;
	private long _followsTo;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SocialFollow, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SocialFollow)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("socialFollowId", _socialFollowId);
		_columnOriginalValues.put("accepted", _accepted);
		_columnOriginalValues.put("followsTo", _followsTo);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("socialFollowId", 2L);

		columnBitmasks.put("accepted", 4L);

		columnBitmasks.put("followsTo", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("companyId", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("userName", 128L);

		columnBitmasks.put("createDate", 256L);

		columnBitmasks.put("modifiedDate", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SocialFollow _escapedModel;

}