/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.calendarbooking.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Protagonist service. Represents a row in the &quot;AVANIS_CALENDAR_Protagonist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>avanis.calendarbooking.sb.model.impl.ProtagonistModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>avanis.calendarbooking.sb.model.impl.ProtagonistImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Protagonist
 * @generated
 */
@ProviderType
public interface ProtagonistModel
	extends BaseModel<Protagonist>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a protagonist model instance should use the {@link Protagonist} interface instead.
	 */

	/**
	 * Returns the primary key of this protagonist.
	 *
	 * @return the primary key of this protagonist
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this protagonist.
	 *
	 * @param primaryKey the primary key of this protagonist
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this protagonist.
	 *
	 * @return the uuid of this protagonist
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this protagonist.
	 *
	 * @param uuid the uuid of this protagonist
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the protagonist ID of this protagonist.
	 *
	 * @return the protagonist ID of this protagonist
	 */
	public long getProtagonistId();

	/**
	 * Sets the protagonist ID of this protagonist.
	 *
	 * @param protagonistId the protagonist ID of this protagonist
	 */
	public void setProtagonistId(long protagonistId);

	/**
	 * Returns the calendar booking ID of this protagonist.
	 *
	 * @return the calendar booking ID of this protagonist
	 */
	public long getCalendarBookingId();

	/**
	 * Sets the calendar booking ID of this protagonist.
	 *
	 * @param calendarBookingId the calendar booking ID of this protagonist
	 */
	public void setCalendarBookingId(long calendarBookingId);

	/**
	 * Returns the group ID of this protagonist.
	 *
	 * @return the group ID of this protagonist
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this protagonist.
	 *
	 * @param groupId the group ID of this protagonist
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this protagonist.
	 *
	 * @return the company ID of this protagonist
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this protagonist.
	 *
	 * @param companyId the company ID of this protagonist
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this protagonist.
	 *
	 * @return the user ID of this protagonist
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this protagonist.
	 *
	 * @param userId the user ID of this protagonist
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this protagonist.
	 *
	 * @return the user uuid of this protagonist
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this protagonist.
	 *
	 * @param userUuid the user uuid of this protagonist
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this protagonist.
	 *
	 * @return the user name of this protagonist
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this protagonist.
	 *
	 * @param userName the user name of this protagonist
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this protagonist.
	 *
	 * @return the create date of this protagonist
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this protagonist.
	 *
	 * @param createDate the create date of this protagonist
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this protagonist.
	 *
	 * @return the modified date of this protagonist
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this protagonist.
	 *
	 * @param modifiedDate the modified date of this protagonist
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this protagonist.
	 *
	 * @return the name of this protagonist
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this protagonist.
	 *
	 * @param name the name of this protagonist
	 */
	public void setName(String name);

	/**
	 * Returns the last name of this protagonist.
	 *
	 * @return the last name of this protagonist
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this protagonist.
	 *
	 * @param lastName the last name of this protagonist
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the profession of this protagonist.
	 *
	 * @return the profession of this protagonist
	 */
	@AutoEscape
	public String getProfession();

	/**
	 * Sets the profession of this protagonist.
	 *
	 * @param profession the profession of this protagonist
	 */
	public void setProfession(String profession);

	/**
	 * Returns the bio of this protagonist.
	 *
	 * @return the bio of this protagonist
	 */
	@AutoEscape
	public String getBio();

	/**
	 * Sets the bio of this protagonist.
	 *
	 * @param bio the bio of this protagonist
	 */
	public void setBio(String bio);

	/**
	 * Returns the portrait url of this protagonist.
	 *
	 * @return the portrait url of this protagonist
	 */
	@AutoEscape
	public String getPortraitUrl();

	/**
	 * Sets the portrait url of this protagonist.
	 *
	 * @param portraitUrl the portrait url of this protagonist
	 */
	public void setPortraitUrl(String portraitUrl);

	@Override
	public Protagonist cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}