/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.thread.logger.sb.model.impl;

import avanis.thread.logger.sb.model.ThreadLog;
import avanis.thread.logger.sb.service.ThreadLogLocalServiceUtil;

/**
 * The extended model base implementation for the ThreadLog service. Represents a row in the &quot;ThreadLogger_ThreadLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThreadLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ThreadLogImpl
 * @see ThreadLog
 * @generated
 */
public abstract class ThreadLogBaseImpl
	extends ThreadLogModelImpl implements ThreadLog {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a thread log model instance should use the <code>ThreadLog</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ThreadLogLocalServiceUtil.addThreadLog(this);
		}
		else {
			ThreadLogLocalServiceUtil.updateThreadLog(this);
		}
	}

}