/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.lonjas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FechaLonja service. Represents a row in the &quot;AVANIS_LONJAS_FechaLonja&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>avanis.lonjas.model.impl.FechaLonjaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>avanis.lonjas.model.impl.FechaLonjaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FechaLonja
 * @generated
 */
@ProviderType
public interface FechaLonjaModel extends BaseModel<FechaLonja> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fecha lonja model instance should use the {@link FechaLonja} interface instead.
	 */

	/**
	 * Returns the primary key of this fecha lonja.
	 *
	 * @return the primary key of this fecha lonja
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fecha lonja.
	 *
	 * @param primaryKey the primary key of this fecha lonja
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this fecha lonja.
	 *
	 * @return the uuid of this fecha lonja
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this fecha lonja.
	 *
	 * @param uuid the uuid of this fecha lonja
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the entity ID of this fecha lonja.
	 *
	 * @return the entity ID of this fecha lonja
	 */
	public long getEntityId();

	/**
	 * Sets the entity ID of this fecha lonja.
	 *
	 * @param entityId the entity ID of this fecha lonja
	 */
	public void setEntityId(long entityId);

	/**
	 * Returns the lonja ID of this fecha lonja.
	 *
	 * @return the lonja ID of this fecha lonja
	 */
	public long getLonjaId();

	/**
	 * Sets the lonja ID of this fecha lonja.
	 *
	 * @param lonjaId the lonja ID of this fecha lonja
	 */
	public void setLonjaId(long lonjaId);

	/**
	 * Returns the fecha of this fecha lonja.
	 *
	 * @return the fecha of this fecha lonja
	 */
	public Date getFecha();

	/**
	 * Sets the fecha of this fecha lonja.
	 *
	 * @param fecha the fecha of this fecha lonja
	 */
	public void setFecha(Date fecha);

	/**
	 * Returns the create date of this fecha lonja.
	 *
	 * @return the create date of this fecha lonja
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this fecha lonja.
	 *
	 * @param createDate the create date of this fecha lonja
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this fecha lonja.
	 *
	 * @return the modified date of this fecha lonja
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this fecha lonja.
	 *
	 * @param modifiedDate the modified date of this fecha lonja
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public FechaLonja cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}