/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.lonjas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Lonja service. Represents a row in the &quot;AVANIS_LONJAS_Lonja&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>avanis.lonjas.model.impl.LonjaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>avanis.lonjas.model.impl.LonjaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Lonja
 * @generated
 */
@ProviderType
public interface LonjaModel extends BaseModel<Lonja> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lonja model instance should use the {@link Lonja} interface instead.
	 */

	/**
	 * Returns the primary key of this lonja.
	 *
	 * @return the primary key of this lonja
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lonja.
	 *
	 * @param primaryKey the primary key of this lonja
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this lonja.
	 *
	 * @return the uuid of this lonja
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this lonja.
	 *
	 * @param uuid the uuid of this lonja
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the entity ID of this lonja.
	 *
	 * @return the entity ID of this lonja
	 */
	public long getEntityId();

	/**
	 * Sets the entity ID of this lonja.
	 *
	 * @param entityId the entity ID of this lonja
	 */
	public void setEntityId(long entityId);

	/**
	 * Returns the lonja ID of this lonja.
	 *
	 * @return the lonja ID of this lonja
	 */
	public long getLonjaId();

	/**
	 * Sets the lonja ID of this lonja.
	 *
	 * @param lonjaId the lonja ID of this lonja
	 */
	public void setLonjaId(long lonjaId);

	/**
	 * Returns the nombre of this lonja.
	 *
	 * @return the nombre of this lonja
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this lonja.
	 *
	 * @param nombre the nombre of this lonja
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the pais of this lonja.
	 *
	 * @return the pais of this lonja
	 */
	@AutoEscape
	public String getPais();

	/**
	 * Sets the pais of this lonja.
	 *
	 * @param pais the pais of this lonja
	 */
	public void setPais(String pais);

	/**
	 * Returns the create date of this lonja.
	 *
	 * @return the create date of this lonja
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this lonja.
	 *
	 * @param createDate the create date of this lonja
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lonja.
	 *
	 * @return the modified date of this lonja
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lonja.
	 *
	 * @param modifiedDate the modified date of this lonja
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Lonja cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}