/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.lonjas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductoExplot service. Represents a row in the &quot;AVANIS_LONJAS_ProductoExplot&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>avanis.lonjas.model.impl.ProductoExplotModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>avanis.lonjas.model.impl.ProductoExplotImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductoExplot
 * @generated
 */
@ProviderType
public interface ProductoExplotModel extends BaseModel<ProductoExplot> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a producto explot model instance should use the {@link ProductoExplot} interface instead.
	 */

	/**
	 * Returns the primary key of this producto explot.
	 *
	 * @return the primary key of this producto explot
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this producto explot.
	 *
	 * @param primaryKey the primary key of this producto explot
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this producto explot.
	 *
	 * @return the uuid of this producto explot
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this producto explot.
	 *
	 * @param uuid the uuid of this producto explot
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the entity ID of this producto explot.
	 *
	 * @return the entity ID of this producto explot
	 */
	public long getEntityId();

	/**
	 * Sets the entity ID of this producto explot.
	 *
	 * @param entityId the entity ID of this producto explot
	 */
	public void setEntityId(long entityId);

	/**
	 * Returns the lonja ID of this producto explot.
	 *
	 * @return the lonja ID of this producto explot
	 */
	public long getLonjaId();

	/**
	 * Sets the lonja ID of this producto explot.
	 *
	 * @param lonjaId the lonja ID of this producto explot
	 */
	public void setLonjaId(long lonjaId);

	/**
	 * Returns the producto ID of this producto explot.
	 *
	 * @return the producto ID of this producto explot
	 */
	public long getProductoId();

	/**
	 * Sets the producto ID of this producto explot.
	 *
	 * @param productoId the producto ID of this producto explot
	 */
	public void setProductoId(long productoId);

	/**
	 * Returns the precio lonja ID of this producto explot.
	 *
	 * @return the precio lonja ID of this producto explot
	 */
	public long getPrecioLonjaId();

	/**
	 * Sets the precio lonja ID of this producto explot.
	 *
	 * @param precioLonjaId the precio lonja ID of this producto explot
	 */
	public void setPrecioLonjaId(long precioLonjaId);

	/**
	 * Returns the explotacion ID of this producto explot.
	 *
	 * @return the explotacion ID of this producto explot
	 */
	public long getExplotacionId();

	/**
	 * Sets the explotacion ID of this producto explot.
	 *
	 * @param explotacionId the explotacion ID of this producto explot
	 */
	public void setExplotacionId(long explotacionId);

	/**
	 * Returns the orden of this producto explot.
	 *
	 * @return the orden of this producto explot
	 */
	public long getOrden();

	/**
	 * Sets the orden of this producto explot.
	 *
	 * @param orden the orden of this producto explot
	 */
	public void setOrden(long orden);

	/**
	 * Returns the create date of this producto explot.
	 *
	 * @return the create date of this producto explot
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this producto explot.
	 *
	 * @param createDate the create date of this producto explot
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this producto explot.
	 *
	 * @return the modified date of this producto explot
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this producto explot.
	 *
	 * @param modifiedDate the modified date of this producto explot
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public ProductoExplot cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}