/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.lonjas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SubGrupo service. Represents a row in the &quot;AVANIS_LONJAS_SubGrupo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>avanis.lonjas.model.impl.SubGrupoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>avanis.lonjas.model.impl.SubGrupoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubGrupo
 * @generated
 */
@ProviderType
public interface SubGrupoModel extends BaseModel<SubGrupo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sub grupo model instance should use the {@link SubGrupo} interface instead.
	 */

	/**
	 * Returns the primary key of this sub grupo.
	 *
	 * @return the primary key of this sub grupo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sub grupo.
	 *
	 * @param primaryKey the primary key of this sub grupo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this sub grupo.
	 *
	 * @return the uuid of this sub grupo
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this sub grupo.
	 *
	 * @param uuid the uuid of this sub grupo
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the entity ID of this sub grupo.
	 *
	 * @return the entity ID of this sub grupo
	 */
	public long getEntityId();

	/**
	 * Sets the entity ID of this sub grupo.
	 *
	 * @param entityId the entity ID of this sub grupo
	 */
	public void setEntityId(long entityId);

	/**
	 * Returns the sub grupo ID of this sub grupo.
	 *
	 * @return the sub grupo ID of this sub grupo
	 */
	public long getSubGrupoId();

	/**
	 * Sets the sub grupo ID of this sub grupo.
	 *
	 * @param subGrupoId the sub grupo ID of this sub grupo
	 */
	public void setSubGrupoId(long subGrupoId);

	/**
	 * Returns the grupo ID of this sub grupo.
	 *
	 * @return the grupo ID of this sub grupo
	 */
	public long getGrupoId();

	/**
	 * Sets the grupo ID of this sub grupo.
	 *
	 * @param grupoId the grupo ID of this sub grupo
	 */
	public void setGrupoId(long grupoId);

	/**
	 * Returns the nombre of this sub grupo.
	 *
	 * @return the nombre of this sub grupo
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this sub grupo.
	 *
	 * @param nombre the nombre of this sub grupo
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the create date of this sub grupo.
	 *
	 * @return the create date of this sub grupo
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this sub grupo.
	 *
	 * @param createDate the create date of this sub grupo
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sub grupo.
	 *
	 * @return the modified date of this sub grupo
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sub grupo.
	 *
	 * @param modifiedDate the modified date of this sub grupo
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public SubGrupo cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}