/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.social.follow.sb.service.base;

import avanis.social.follow.sb.model.SocialFollow;
import avanis.social.follow.sb.service.SocialFollowService;
import avanis.social.follow.sb.service.SocialFollowServiceUtil;
import avanis.social.follow.sb.service.persistence.SocialFollowPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the social follow remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link avanis.social.follow.sb.service.impl.SocialFollowServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see avanis.social.follow.sb.service.impl.SocialFollowServiceImpl
 * @generated
 */
public abstract class SocialFollowServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, SocialFollowService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SocialFollowService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>SocialFollowServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		SocialFollowServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SocialFollowService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		socialFollowService = (SocialFollowService)aopProxy;

		SocialFollowServiceUtil.setService(socialFollowService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SocialFollowService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SocialFollow.class;
	}

	protected String getModelClassName() {
		return SocialFollow.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = socialFollowPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected avanis.social.follow.sb.service.SocialFollowLocalService
		socialFollowLocalService;

	protected SocialFollowService socialFollowService;

	@Reference
	protected SocialFollowPersistence socialFollowPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		SocialFollowServiceBaseImpl.class);

}