/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.social.follow.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SocialFollow service. Represents a row in the &quot;SOCIAL_FOLLOW_SocialFollow&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>avanis.social.follow.sb.model.impl.SocialFollowModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>avanis.social.follow.sb.model.impl.SocialFollowImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SocialFollow
 * @generated
 */
@ProviderType
public interface SocialFollowModel
	extends BaseModel<SocialFollow>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a social follow model instance should use the {@link SocialFollow} interface instead.
	 */

	/**
	 * Returns the primary key of this social follow.
	 *
	 * @return the primary key of this social follow
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this social follow.
	 *
	 * @param primaryKey the primary key of this social follow
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this social follow.
	 *
	 * @return the uuid of this social follow
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this social follow.
	 *
	 * @param uuid the uuid of this social follow
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the social follow ID of this social follow.
	 *
	 * @return the social follow ID of this social follow
	 */
	public long getSocialFollowId();

	/**
	 * Sets the social follow ID of this social follow.
	 *
	 * @param socialFollowId the social follow ID of this social follow
	 */
	public void setSocialFollowId(long socialFollowId);

	/**
	 * Returns the accepted of this social follow.
	 *
	 * @return the accepted of this social follow
	 */
	public boolean getAccepted();

	/**
	 * Returns <code>true</code> if this social follow is accepted.
	 *
	 * @return <code>true</code> if this social follow is accepted; <code>false</code> otherwise
	 */
	public boolean isAccepted();

	/**
	 * Sets whether this social follow is accepted.
	 *
	 * @param accepted the accepted of this social follow
	 */
	public void setAccepted(boolean accepted);

	/**
	 * Returns the follows to of this social follow.
	 *
	 * @return the follows to of this social follow
	 */
	public long getFollowsTo();

	/**
	 * Sets the follows to of this social follow.
	 *
	 * @param followsTo the follows to of this social follow
	 */
	public void setFollowsTo(long followsTo);

	/**
	 * Returns the group ID of this social follow.
	 *
	 * @return the group ID of this social follow
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this social follow.
	 *
	 * @param groupId the group ID of this social follow
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this social follow.
	 *
	 * @return the company ID of this social follow
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this social follow.
	 *
	 * @param companyId the company ID of this social follow
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this social follow.
	 *
	 * @return the user ID of this social follow
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this social follow.
	 *
	 * @param userId the user ID of this social follow
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this social follow.
	 *
	 * @return the user uuid of this social follow
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this social follow.
	 *
	 * @param userUuid the user uuid of this social follow
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this social follow.
	 *
	 * @return the user name of this social follow
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this social follow.
	 *
	 * @param userName the user name of this social follow
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this social follow.
	 *
	 * @return the create date of this social follow
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this social follow.
	 *
	 * @param createDate the create date of this social follow
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this social follow.
	 *
	 * @return the modified date of this social follow
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this social follow.
	 *
	 * @param modifiedDate the modified date of this social follow
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public SocialFollow cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}