/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.comunidad.model.impl;

import avanis.comunidad.model.AnswersUser;
import avanis.comunidad.model.AnswersUserModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AnswersUser service. Represents a row in the &quot;AVANIS_COMUNIDAD_AnswersUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AnswersUserModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnswersUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnswersUserImpl
 * @generated
 */
@JSON(strict = true)
public class AnswersUserModelImpl
	extends BaseModelImpl<AnswersUser> implements AnswersUserModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a answers user model instance should use the <code>AnswersUser</code> interface instead.
	 */
	public static final String TABLE_NAME = "AVANIS_COMUNIDAD_AnswersUser";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"answerUserId", Types.BIGINT},
		{"answerId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"surveyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("answerUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("answerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("surveyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AVANIS_COMUNIDAD_AnswersUser (uuid_ VARCHAR(75) null,answerUserId LONG not null primary key,answerId LONG,userId LONG,surveyId LONG,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table AVANIS_COMUNIDAD_AnswersUser";

	public static final String ORDER_BY_JPQL =
		" ORDER BY answersUser.modifiedDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AVANIS_COMUNIDAD_AnswersUser.modifiedDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ANSWERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SURVEYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AnswersUserModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _answerUserId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAnswerUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _answerUserId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AnswersUser.class;
	}

	@Override
	public String getModelClassName() {
		return AnswersUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AnswersUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AnswersUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnswersUser, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AnswersUser)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AnswersUser, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AnswersUser, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AnswersUser)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AnswersUser, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AnswersUser, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AnswersUser, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AnswersUser, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<AnswersUser, Object>>();

			attributeGetterFunctions.put("uuid", AnswersUser::getUuid);
			attributeGetterFunctions.put(
				"answerUserId", AnswersUser::getAnswerUserId);
			attributeGetterFunctions.put("answerId", AnswersUser::getAnswerId);
			attributeGetterFunctions.put("userId", AnswersUser::getUserId);
			attributeGetterFunctions.put("surveyId", AnswersUser::getSurveyId);
			attributeGetterFunctions.put(
				"createDate", AnswersUser::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AnswersUser::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AnswersUser, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AnswersUser, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<AnswersUser, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<AnswersUser, String>)AnswersUser::setUuid);
			attributeSetterBiConsumers.put(
				"answerUserId",
				(BiConsumer<AnswersUser, Long>)AnswersUser::setAnswerUserId);
			attributeSetterBiConsumers.put(
				"answerId",
				(BiConsumer<AnswersUser, Long>)AnswersUser::setAnswerId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<AnswersUser, Long>)AnswersUser::setUserId);
			attributeSetterBiConsumers.put(
				"surveyId",
				(BiConsumer<AnswersUser, Long>)AnswersUser::setSurveyId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AnswersUser, Date>)AnswersUser::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AnswersUser, Date>)AnswersUser::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAnswerUserId() {
		return _answerUserId;
	}

	@Override
	public void setAnswerUserId(long answerUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_answerUserId = answerUserId;
	}

	@Override
	public String getAnswerUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getAnswerUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setAnswerUserUuid(String answerUserUuid) {
	}

	@JSON
	@Override
	public long getAnswerId() {
		return _answerId;
	}

	@Override
	public void setAnswerId(long answerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_answerId = answerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAnswerId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("answerId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public long getSurveyId() {
		return _surveyId;
	}

	@Override
	public void setSurveyId(long surveyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_surveyId = surveyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSurveyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("surveyId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AnswersUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AnswersUser toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AnswersUser>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AnswersUserImpl answersUserImpl = new AnswersUserImpl();

		answersUserImpl.setUuid(getUuid());
		answersUserImpl.setAnswerUserId(getAnswerUserId());
		answersUserImpl.setAnswerId(getAnswerId());
		answersUserImpl.setUserId(getUserId());
		answersUserImpl.setSurveyId(getSurveyId());
		answersUserImpl.setCreateDate(getCreateDate());
		answersUserImpl.setModifiedDate(getModifiedDate());

		answersUserImpl.resetOriginalValues();

		return answersUserImpl;
	}

	@Override
	public AnswersUser cloneWithOriginalValues() {
		AnswersUserImpl answersUserImpl = new AnswersUserImpl();

		answersUserImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		answersUserImpl.setAnswerUserId(
			this.<Long>getColumnOriginalValue("answerUserId"));
		answersUserImpl.setAnswerId(
			this.<Long>getColumnOriginalValue("answerId"));
		answersUserImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		answersUserImpl.setSurveyId(
			this.<Long>getColumnOriginalValue("surveyId"));
		answersUserImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		answersUserImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return answersUserImpl;
	}

	@Override
	public int compareTo(AnswersUser answersUser) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), answersUser.getModifiedDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AnswersUser)) {
			return false;
		}

		AnswersUser answersUser = (AnswersUser)object;

		long primaryKey = answersUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AnswersUser> toCacheModel() {
		AnswersUserCacheModel answersUserCacheModel =
			new AnswersUserCacheModel();

		answersUserCacheModel.uuid = getUuid();

		String uuid = answersUserCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			answersUserCacheModel.uuid = null;
		}

		answersUserCacheModel.answerUserId = getAnswerUserId();

		answersUserCacheModel.answerId = getAnswerId();

		answersUserCacheModel.userId = getUserId();

		answersUserCacheModel.surveyId = getSurveyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			answersUserCacheModel.createDate = createDate.getTime();
		}
		else {
			answersUserCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			answersUserCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			answersUserCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return answersUserCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AnswersUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AnswersUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnswersUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AnswersUser)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AnswersUser>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AnswersUser.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _answerUserId;
	private long _answerId;
	private long _userId;
	private long _surveyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AnswersUser, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AnswersUser)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("answerUserId", _answerUserId);
		_columnOriginalValues.put("answerId", _answerId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("surveyId", _surveyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("answerUserId", 2L);

		columnBitmasks.put("answerId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("surveyId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AnswersUser _escapedModel;

}