/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.comunidad.model.impl;

import avanis.comunidad.model.AnswersUser;
import avanis.comunidad.service.AnswersUserLocalServiceUtil;

/**
 * The extended model base implementation for the AnswersUser service. Represents a row in the &quot;AVANIS_COMUNIDAD_AnswersUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnswersUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnswersUserImpl
 * @see AnswersUser
 * @generated
 */
public abstract class AnswersUserBaseImpl
	extends AnswersUserModelImpl implements AnswersUser {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a answers user model instance should use the <code>AnswersUser</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AnswersUserLocalServiceUtil.addAnswersUser(this);
		}
		else {
			AnswersUserLocalServiceUtil.updateAnswersUser(this);
		}
	}

}