/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.comunidad.model.impl;

import avanis.comunidad.model.Surveys;
import avanis.comunidad.service.SurveysLocalServiceUtil;

/**
 * The extended model base implementation for the Surveys service. Represents a row in the &quot;AVANIS_COMUNIDAD_Surveys&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SurveysImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SurveysImpl
 * @see Surveys
 * @generated
 */
public abstract class SurveysBaseImpl
	extends SurveysModelImpl implements Surveys {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a surveys model instance should use the <code>Surveys</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SurveysLocalServiceUtil.addSurveys(this);
		}
		else {
			SurveysLocalServiceUtil.updateSurveys(this);
		}
	}

}