/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.comunidad.model.impl;

import avanis.comunidad.model.Surveys;
import avanis.comunidad.model.SurveysModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Surveys service. Represents a row in the &quot;AVANIS_COMUNIDAD_Surveys&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SurveysModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SurveysImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SurveysImpl
 * @generated
 */
@JSON(strict = true)
public class SurveysModelImpl
	extends BaseModelImpl<Surveys> implements SurveysModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a surveys model instance should use the <code>Surveys</code> interface instead.
	 */
	public static final String TABLE_NAME = "AVANIS_COMUNIDAD_Surveys";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"surveyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"assetId", Types.BIGINT}, {"question", Types.VARCHAR},
		{"expireHours", Types.INTEGER}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"expireDate", Types.TIMESTAMP},
		{"notified", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("surveyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("question", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("expireHours", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expireDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("notified", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AVANIS_COMUNIDAD_Surveys (uuid_ VARCHAR(75) null,surveyId LONG not null primary key,groupId LONG,userId LONG,assetId LONG,question VARCHAR(255) null,expireHours INTEGER,createDate DATE null,modifiedDate DATE null,expireDate DATE null,notified BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table AVANIS_COMUNIDAD_Surveys";

	public static final String ORDER_BY_JPQL =
		" ORDER BY surveys.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AVANIS_COMUNIDAD_Surveys.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ASSETID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SurveysModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _surveyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSurveyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _surveyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Surveys.class;
	}

	@Override
	public String getModelClassName() {
		return Surveys.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Surveys, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Surveys, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Surveys, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Surveys)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Surveys, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Surveys, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Surveys)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Surveys, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Surveys, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Surveys, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Surveys, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Surveys, Object>>();

			attributeGetterFunctions.put("uuid", Surveys::getUuid);
			attributeGetterFunctions.put("surveyId", Surveys::getSurveyId);
			attributeGetterFunctions.put("groupId", Surveys::getGroupId);
			attributeGetterFunctions.put("userId", Surveys::getUserId);
			attributeGetterFunctions.put("assetId", Surveys::getAssetId);
			attributeGetterFunctions.put("question", Surveys::getQuestion);
			attributeGetterFunctions.put(
				"expireHours", Surveys::getExpireHours);
			attributeGetterFunctions.put("createDate", Surveys::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Surveys::getModifiedDate);
			attributeGetterFunctions.put("expireDate", Surveys::getExpireDate);
			attributeGetterFunctions.put("notified", Surveys::getNotified);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Surveys, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Surveys, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Surveys, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Surveys, String>)Surveys::setUuid);
			attributeSetterBiConsumers.put(
				"surveyId", (BiConsumer<Surveys, Long>)Surveys::setSurveyId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Surveys, Long>)Surveys::setGroupId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Surveys, Long>)Surveys::setUserId);
			attributeSetterBiConsumers.put(
				"assetId", (BiConsumer<Surveys, Long>)Surveys::setAssetId);
			attributeSetterBiConsumers.put(
				"question", (BiConsumer<Surveys, String>)Surveys::setQuestion);
			attributeSetterBiConsumers.put(
				"expireHours",
				(BiConsumer<Surveys, Integer>)Surveys::setExpireHours);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Surveys, Date>)Surveys::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Surveys, Date>)Surveys::setModifiedDate);
			attributeSetterBiConsumers.put(
				"expireDate",
				(BiConsumer<Surveys, Date>)Surveys::setExpireDate);
			attributeSetterBiConsumers.put(
				"notified", (BiConsumer<Surveys, Boolean>)Surveys::setNotified);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getSurveyId() {
		return _surveyId;
	}

	@Override
	public void setSurveyId(long surveyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_surveyId = surveyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public long getAssetId() {
		return _assetId;
	}

	@Override
	public void setAssetId(long assetId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assetId = assetId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAssetId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("assetId"));
	}

	@JSON
	@Override
	public String getQuestion() {
		if (_question == null) {
			return "";
		}
		else {
			return _question;
		}
	}

	@Override
	public void setQuestion(String question) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_question = question;
	}

	@JSON
	@Override
	public int getExpireHours() {
		return _expireHours;
	}

	@Override
	public void setExpireHours(int expireHours) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expireHours = expireHours;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getExpireDate() {
		return _expireDate;
	}

	@Override
	public void setExpireDate(Date expireDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expireDate = expireDate;
	}

	@JSON
	@Override
	public Boolean getNotified() {
		return _notified;
	}

	@Override
	public void setNotified(Boolean notified) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notified = notified;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Surveys.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Surveys toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Surveys>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SurveysImpl surveysImpl = new SurveysImpl();

		surveysImpl.setUuid(getUuid());
		surveysImpl.setSurveyId(getSurveyId());
		surveysImpl.setGroupId(getGroupId());
		surveysImpl.setUserId(getUserId());
		surveysImpl.setAssetId(getAssetId());
		surveysImpl.setQuestion(getQuestion());
		surveysImpl.setExpireHours(getExpireHours());
		surveysImpl.setCreateDate(getCreateDate());
		surveysImpl.setModifiedDate(getModifiedDate());
		surveysImpl.setExpireDate(getExpireDate());
		surveysImpl.setNotified(getNotified());

		surveysImpl.resetOriginalValues();

		return surveysImpl;
	}

	@Override
	public Surveys cloneWithOriginalValues() {
		SurveysImpl surveysImpl = new SurveysImpl();

		surveysImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		surveysImpl.setSurveyId(this.<Long>getColumnOriginalValue("surveyId"));
		surveysImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		surveysImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		surveysImpl.setAssetId(this.<Long>getColumnOriginalValue("assetId"));
		surveysImpl.setQuestion(
			this.<String>getColumnOriginalValue("question"));
		surveysImpl.setExpireHours(
			this.<Integer>getColumnOriginalValue("expireHours"));
		surveysImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		surveysImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		surveysImpl.setExpireDate(
			this.<Date>getColumnOriginalValue("expireDate"));
		surveysImpl.setNotified(
			this.<Boolean>getColumnOriginalValue("notified"));

		return surveysImpl;
	}

	@Override
	public int compareTo(Surveys surveys) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), surveys.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Surveys)) {
			return false;
		}

		Surveys surveys = (Surveys)object;

		long primaryKey = surveys.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Surveys> toCacheModel() {
		SurveysCacheModel surveysCacheModel = new SurveysCacheModel();

		surveysCacheModel.uuid = getUuid();

		String uuid = surveysCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			surveysCacheModel.uuid = null;
		}

		surveysCacheModel.surveyId = getSurveyId();

		surveysCacheModel.groupId = getGroupId();

		surveysCacheModel.userId = getUserId();

		surveysCacheModel.assetId = getAssetId();

		surveysCacheModel.question = getQuestion();

		String question = surveysCacheModel.question;

		if ((question != null) && (question.length() == 0)) {
			surveysCacheModel.question = null;
		}

		surveysCacheModel.expireHours = getExpireHours();

		Date createDate = getCreateDate();

		if (createDate != null) {
			surveysCacheModel.createDate = createDate.getTime();
		}
		else {
			surveysCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			surveysCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			surveysCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date expireDate = getExpireDate();

		if (expireDate != null) {
			surveysCacheModel.expireDate = expireDate.getTime();
		}
		else {
			surveysCacheModel.expireDate = Long.MIN_VALUE;
		}

		Boolean notified = getNotified();

		if (notified != null) {
			surveysCacheModel.notified = notified;
		}

		return surveysCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Surveys, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Surveys, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Surveys, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Surveys)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Surveys>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Surveys.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _surveyId;
	private long _groupId;
	private long _userId;
	private long _assetId;
	private String _question;
	private int _expireHours;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _expireDate;
	private Boolean _notified;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Surveys, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Surveys)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("surveyId", _surveyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("assetId", _assetId);
		_columnOriginalValues.put("question", _question);
		_columnOriginalValues.put("expireHours", _expireHours);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("expireDate", _expireDate);
		_columnOriginalValues.put("notified", _notified);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("surveyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("assetId", 16L);

		columnBitmasks.put("question", 32L);

		columnBitmasks.put("expireHours", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("expireDate", 512L);

		columnBitmasks.put("notified", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Surveys _escapedModel;

}