/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.calendarbooking.sb.model.impl;

import avanis.calendarbooking.sb.model.BookingAgenda;
import avanis.calendarbooking.sb.model.BookingAgendaModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BookingAgenda service. Represents a row in the &quot;AVANIS_CALENDAR_BookingAgenda&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BookingAgendaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookingAgendaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BookingAgendaImpl
 * @generated
 */
@JSON(strict = true)
public class BookingAgendaModelImpl
	extends BaseModelImpl<BookingAgenda> implements BookingAgendaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a booking agenda model instance should use the <code>BookingAgenda</code> interface instead.
	 */
	public static final String TABLE_NAME = "AVANIS_CALENDAR_BookingAgenda";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"calendarBookingAgendaId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"day", Types.BIGINT}, {"startHour", Types.BIGINT},
		{"endHour", Types.BIGINT}, {"title", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"calendarBookingId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("calendarBookingAgendaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("day", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startHour", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("endHour", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("calendarBookingId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AVANIS_CALENDAR_BookingAgenda (uuid_ VARCHAR(75) null,calendarBookingAgendaId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,day LONG,startHour LONG,endHour LONG,title VARCHAR(75) null,description VARCHAR(75) null,calendarBookingId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table AVANIS_CALENDAR_BookingAgenda";

	public static final String ORDER_BY_JPQL =
		" ORDER BY bookingAgenda.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AVANIS_CALENDAR_BookingAgenda.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CALENDARBOOKINGID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BookingAgendaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _calendarBookingAgendaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCalendarBookingAgendaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _calendarBookingAgendaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BookingAgenda.class;
	}

	@Override
	public String getModelClassName() {
		return BookingAgenda.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BookingAgenda, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BookingAgenda, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BookingAgenda, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BookingAgenda)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BookingAgenda, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BookingAgenda, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BookingAgenda)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BookingAgenda, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BookingAgenda, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<BookingAgenda, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<BookingAgenda, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<BookingAgenda, Object>>();

			attributeGetterFunctions.put("uuid", BookingAgenda::getUuid);
			attributeGetterFunctions.put(
				"calendarBookingAgendaId",
				BookingAgenda::getCalendarBookingAgendaId);
			attributeGetterFunctions.put("groupId", BookingAgenda::getGroupId);
			attributeGetterFunctions.put(
				"companyId", BookingAgenda::getCompanyId);
			attributeGetterFunctions.put("userId", BookingAgenda::getUserId);
			attributeGetterFunctions.put(
				"userName", BookingAgenda::getUserName);
			attributeGetterFunctions.put(
				"createDate", BookingAgenda::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", BookingAgenda::getModifiedDate);
			attributeGetterFunctions.put("day", BookingAgenda::getDay);
			attributeGetterFunctions.put(
				"startHour", BookingAgenda::getStartHour);
			attributeGetterFunctions.put("endHour", BookingAgenda::getEndHour);
			attributeGetterFunctions.put("title", BookingAgenda::getTitle);
			attributeGetterFunctions.put(
				"description", BookingAgenda::getDescription);
			attributeGetterFunctions.put(
				"calendarBookingId", BookingAgenda::getCalendarBookingId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<BookingAgenda, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BookingAgenda, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<BookingAgenda, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<BookingAgenda, String>)BookingAgenda::setUuid);
			attributeSetterBiConsumers.put(
				"calendarBookingAgendaId",
				(BiConsumer<BookingAgenda, Long>)
					BookingAgenda::setCalendarBookingAgendaId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<BookingAgenda, Long>)BookingAgenda::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<BookingAgenda, Long>)BookingAgenda::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<BookingAgenda, Long>)BookingAgenda::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<BookingAgenda, String>)BookingAgenda::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<BookingAgenda, Date>)BookingAgenda::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<BookingAgenda, Date>)
					BookingAgenda::setModifiedDate);
			attributeSetterBiConsumers.put(
				"day", (BiConsumer<BookingAgenda, Long>)BookingAgenda::setDay);
			attributeSetterBiConsumers.put(
				"startHour",
				(BiConsumer<BookingAgenda, Long>)BookingAgenda::setStartHour);
			attributeSetterBiConsumers.put(
				"endHour",
				(BiConsumer<BookingAgenda, Long>)BookingAgenda::setEndHour);
			attributeSetterBiConsumers.put(
				"title",
				(BiConsumer<BookingAgenda, String>)BookingAgenda::setTitle);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<BookingAgenda, String>)
					BookingAgenda::setDescription);
			attributeSetterBiConsumers.put(
				"calendarBookingId",
				(BiConsumer<BookingAgenda, Long>)
					BookingAgenda::setCalendarBookingId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCalendarBookingAgendaId() {
		return _calendarBookingAgendaId;
	}

	@Override
	public void setCalendarBookingAgendaId(long calendarBookingAgendaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_calendarBookingAgendaId = calendarBookingAgendaId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getDay() {
		return _day;
	}

	@Override
	public void setDay(long day) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_day = day;
	}

	@JSON
	@Override
	public long getStartHour() {
		return _startHour;
	}

	@Override
	public void setStartHour(long startHour) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startHour = startHour;
	}

	@JSON
	@Override
	public long getEndHour() {
		return _endHour;
	}

	@Override
	public void setEndHour(long endHour) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endHour = endHour;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public long getCalendarBookingId() {
		return _calendarBookingId;
	}

	@Override
	public void setCalendarBookingId(long calendarBookingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_calendarBookingId = calendarBookingId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCalendarBookingId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("calendarBookingId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(BookingAgenda.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), BookingAgenda.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BookingAgenda toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BookingAgenda>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BookingAgendaImpl bookingAgendaImpl = new BookingAgendaImpl();

		bookingAgendaImpl.setUuid(getUuid());
		bookingAgendaImpl.setCalendarBookingAgendaId(
			getCalendarBookingAgendaId());
		bookingAgendaImpl.setGroupId(getGroupId());
		bookingAgendaImpl.setCompanyId(getCompanyId());
		bookingAgendaImpl.setUserId(getUserId());
		bookingAgendaImpl.setUserName(getUserName());
		bookingAgendaImpl.setCreateDate(getCreateDate());
		bookingAgendaImpl.setModifiedDate(getModifiedDate());
		bookingAgendaImpl.setDay(getDay());
		bookingAgendaImpl.setStartHour(getStartHour());
		bookingAgendaImpl.setEndHour(getEndHour());
		bookingAgendaImpl.setTitle(getTitle());
		bookingAgendaImpl.setDescription(getDescription());
		bookingAgendaImpl.setCalendarBookingId(getCalendarBookingId());

		bookingAgendaImpl.resetOriginalValues();

		return bookingAgendaImpl;
	}

	@Override
	public BookingAgenda cloneWithOriginalValues() {
		BookingAgendaImpl bookingAgendaImpl = new BookingAgendaImpl();

		bookingAgendaImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		bookingAgendaImpl.setCalendarBookingAgendaId(
			this.<Long>getColumnOriginalValue("calendarBookingAgendaId"));
		bookingAgendaImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		bookingAgendaImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		bookingAgendaImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		bookingAgendaImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		bookingAgendaImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		bookingAgendaImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		bookingAgendaImpl.setDay(this.<Long>getColumnOriginalValue("day"));
		bookingAgendaImpl.setStartHour(
			this.<Long>getColumnOriginalValue("startHour"));
		bookingAgendaImpl.setEndHour(
			this.<Long>getColumnOriginalValue("endHour"));
		bookingAgendaImpl.setTitle(
			this.<String>getColumnOriginalValue("title"));
		bookingAgendaImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		bookingAgendaImpl.setCalendarBookingId(
			this.<Long>getColumnOriginalValue("calendarBookingId"));

		return bookingAgendaImpl;
	}

	@Override
	public int compareTo(BookingAgenda bookingAgenda) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), bookingAgenda.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BookingAgenda)) {
			return false;
		}

		BookingAgenda bookingAgenda = (BookingAgenda)object;

		long primaryKey = bookingAgenda.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BookingAgenda> toCacheModel() {
		BookingAgendaCacheModel bookingAgendaCacheModel =
			new BookingAgendaCacheModel();

		bookingAgendaCacheModel.uuid = getUuid();

		String uuid = bookingAgendaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			bookingAgendaCacheModel.uuid = null;
		}

		bookingAgendaCacheModel.calendarBookingAgendaId =
			getCalendarBookingAgendaId();

		bookingAgendaCacheModel.groupId = getGroupId();

		bookingAgendaCacheModel.companyId = getCompanyId();

		bookingAgendaCacheModel.userId = getUserId();

		bookingAgendaCacheModel.userName = getUserName();

		String userName = bookingAgendaCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			bookingAgendaCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			bookingAgendaCacheModel.createDate = createDate.getTime();
		}
		else {
			bookingAgendaCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			bookingAgendaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			bookingAgendaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		bookingAgendaCacheModel.day = getDay();

		bookingAgendaCacheModel.startHour = getStartHour();

		bookingAgendaCacheModel.endHour = getEndHour();

		bookingAgendaCacheModel.title = getTitle();

		String title = bookingAgendaCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			bookingAgendaCacheModel.title = null;
		}

		bookingAgendaCacheModel.description = getDescription();

		String description = bookingAgendaCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			bookingAgendaCacheModel.description = null;
		}

		bookingAgendaCacheModel.calendarBookingId = getCalendarBookingId();

		return bookingAgendaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BookingAgenda, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BookingAgenda, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BookingAgenda, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((BookingAgenda)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BookingAgenda>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BookingAgenda.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _calendarBookingAgendaId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _day;
	private long _startHour;
	private long _endHour;
	private String _title;
	private String _description;
	private long _calendarBookingId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<BookingAgenda, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BookingAgenda)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"calendarBookingAgendaId", _calendarBookingAgendaId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("day", _day);
		_columnOriginalValues.put("startHour", _startHour);
		_columnOriginalValues.put("endHour", _endHour);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("calendarBookingId", _calendarBookingId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("calendarBookingAgendaId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("day", 256L);

		columnBitmasks.put("startHour", 512L);

		columnBitmasks.put("endHour", 1024L);

		columnBitmasks.put("title", 2048L);

		columnBitmasks.put("description", 4096L);

		columnBitmasks.put("calendarBookingId", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BookingAgenda _escapedModel;

}