/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.calendarbooking.sb.model.impl;

import avanis.calendarbooking.sb.model.Protagonist;
import avanis.calendarbooking.sb.service.ProtagonistLocalServiceUtil;

/**
 * The extended model base implementation for the Protagonist service. Represents a row in the &quot;AVANIS_CALENDAR_Protagonist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProtagonistImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProtagonistImpl
 * @see Protagonist
 * @generated
 */
public abstract class ProtagonistBaseImpl
	extends ProtagonistModelImpl implements Protagonist {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a protagonist model instance should use the <code>Protagonist</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ProtagonistLocalServiceUtil.addProtagonist(this);
		}
		else {
			ProtagonistLocalServiceUtil.updateProtagonist(this);
		}
	}

}