/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package avanis.calendarbooking.sb.model.impl;

import avanis.calendarbooking.sb.model.Sponsor;
import avanis.calendarbooking.sb.model.SponsorModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Sponsor service. Represents a row in the &quot;AVANIS_CALENDAR_Sponsor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SponsorModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SponsorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SponsorImpl
 * @generated
 */
@JSON(strict = true)
public class SponsorModelImpl
	extends BaseModelImpl<Sponsor> implements SponsorModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sponsor model instance should use the <code>Sponsor</code> interface instead.
	 */
	public static final String TABLE_NAME = "AVANIS_CALENDAR_Sponsor";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"sponsorId", Types.BIGINT},
		{"calendarBookingId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"iconUrl", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sponsorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("calendarBookingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("iconUrl", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AVANIS_CALENDAR_Sponsor (uuid_ VARCHAR(75) null,sponsorId LONG not null primary key,calendarBookingId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,iconUrl VARCHAR(500) null)";

	public static final String TABLE_SQL_DROP =
		"drop table AVANIS_CALENDAR_Sponsor";

	public static final String ORDER_BY_JPQL =
		" ORDER BY sponsor.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AVANIS_CALENDAR_Sponsor.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CALENDARBOOKINGID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SponsorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _sponsorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSponsorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sponsorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Sponsor.class;
	}

	@Override
	public String getModelClassName() {
		return Sponsor.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Sponsor, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Sponsor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Sponsor, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Sponsor)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Sponsor, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Sponsor, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Sponsor)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Sponsor, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Sponsor, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Sponsor, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Sponsor, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Sponsor, Object>>();

			attributeGetterFunctions.put("uuid", Sponsor::getUuid);
			attributeGetterFunctions.put("sponsorId", Sponsor::getSponsorId);
			attributeGetterFunctions.put(
				"calendarBookingId", Sponsor::getCalendarBookingId);
			attributeGetterFunctions.put("groupId", Sponsor::getGroupId);
			attributeGetterFunctions.put("companyId", Sponsor::getCompanyId);
			attributeGetterFunctions.put("userId", Sponsor::getUserId);
			attributeGetterFunctions.put("userName", Sponsor::getUserName);
			attributeGetterFunctions.put("createDate", Sponsor::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Sponsor::getModifiedDate);
			attributeGetterFunctions.put("name", Sponsor::getName);
			attributeGetterFunctions.put("iconUrl", Sponsor::getIconUrl);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Sponsor, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Sponsor, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Sponsor, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Sponsor, String>)Sponsor::setUuid);
			attributeSetterBiConsumers.put(
				"sponsorId", (BiConsumer<Sponsor, Long>)Sponsor::setSponsorId);
			attributeSetterBiConsumers.put(
				"calendarBookingId",
				(BiConsumer<Sponsor, Long>)Sponsor::setCalendarBookingId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Sponsor, Long>)Sponsor::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Sponsor, Long>)Sponsor::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Sponsor, Long>)Sponsor::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Sponsor, String>)Sponsor::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Sponsor, Date>)Sponsor::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Sponsor, Date>)Sponsor::setModifiedDate);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<Sponsor, String>)Sponsor::setName);
			attributeSetterBiConsumers.put(
				"iconUrl", (BiConsumer<Sponsor, String>)Sponsor::setIconUrl);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getSponsorId() {
		return _sponsorId;
	}

	@Override
	public void setSponsorId(long sponsorId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sponsorId = sponsorId;
	}

	@JSON
	@Override
	public long getCalendarBookingId() {
		return _calendarBookingId;
	}

	@Override
	public void setCalendarBookingId(long calendarBookingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_calendarBookingId = calendarBookingId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCalendarBookingId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("calendarBookingId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getIconUrl() {
		if (_iconUrl == null) {
			return "";
		}
		else {
			return _iconUrl;
		}
	}

	@Override
	public void setIconUrl(String iconUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_iconUrl = iconUrl;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Sponsor.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Sponsor.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Sponsor toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Sponsor>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SponsorImpl sponsorImpl = new SponsorImpl();

		sponsorImpl.setUuid(getUuid());
		sponsorImpl.setSponsorId(getSponsorId());
		sponsorImpl.setCalendarBookingId(getCalendarBookingId());
		sponsorImpl.setGroupId(getGroupId());
		sponsorImpl.setCompanyId(getCompanyId());
		sponsorImpl.setUserId(getUserId());
		sponsorImpl.setUserName(getUserName());
		sponsorImpl.setCreateDate(getCreateDate());
		sponsorImpl.setModifiedDate(getModifiedDate());
		sponsorImpl.setName(getName());
		sponsorImpl.setIconUrl(getIconUrl());

		sponsorImpl.resetOriginalValues();

		return sponsorImpl;
	}

	@Override
	public Sponsor cloneWithOriginalValues() {
		SponsorImpl sponsorImpl = new SponsorImpl();

		sponsorImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		sponsorImpl.setSponsorId(
			this.<Long>getColumnOriginalValue("sponsorId"));
		sponsorImpl.setCalendarBookingId(
			this.<Long>getColumnOriginalValue("calendarBookingId"));
		sponsorImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		sponsorImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		sponsorImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		sponsorImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		sponsorImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		sponsorImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		sponsorImpl.setName(this.<String>getColumnOriginalValue("name"));
		sponsorImpl.setIconUrl(this.<String>getColumnOriginalValue("iconUrl"));

		return sponsorImpl;
	}

	@Override
	public int compareTo(Sponsor sponsor) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), sponsor.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Sponsor)) {
			return false;
		}

		Sponsor sponsor = (Sponsor)object;

		long primaryKey = sponsor.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Sponsor> toCacheModel() {
		SponsorCacheModel sponsorCacheModel = new SponsorCacheModel();

		sponsorCacheModel.uuid = getUuid();

		String uuid = sponsorCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			sponsorCacheModel.uuid = null;
		}

		sponsorCacheModel.sponsorId = getSponsorId();

		sponsorCacheModel.calendarBookingId = getCalendarBookingId();

		sponsorCacheModel.groupId = getGroupId();

		sponsorCacheModel.companyId = getCompanyId();

		sponsorCacheModel.userId = getUserId();

		sponsorCacheModel.userName = getUserName();

		String userName = sponsorCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			sponsorCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			sponsorCacheModel.createDate = createDate.getTime();
		}
		else {
			sponsorCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			sponsorCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			sponsorCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		sponsorCacheModel.name = getName();

		String name = sponsorCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			sponsorCacheModel.name = null;
		}

		sponsorCacheModel.iconUrl = getIconUrl();

		String iconUrl = sponsorCacheModel.iconUrl;

		if ((iconUrl != null) && (iconUrl.length() == 0)) {
			sponsorCacheModel.iconUrl = null;
		}

		return sponsorCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Sponsor, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Sponsor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Sponsor, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Sponsor)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Sponsor>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Sponsor.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _sponsorId;
	private long _calendarBookingId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _iconUrl;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Sponsor, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Sponsor)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("sponsorId", _sponsorId);
		_columnOriginalValues.put("calendarBookingId", _calendarBookingId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("iconUrl", _iconUrl);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("sponsorId", 2L);

		columnBitmasks.put("calendarBookingId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("name", 512L);

		columnBitmasks.put("iconUrl", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Sponsor _escapedModel;

}